function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('bmci', 'BMW M5')
	AddTextEntry('c63', 'Mercedes C63 AMG')
	AddTextEntry('cb500f', 'Honda CB500F 2018')
	AddTextEntry('cls53', 'Mercedes CLS53 AMG')
	AddTextEntry('dodgeEMS', 'Dodge EMS')
	AddTextEntry('fct', 'Ferrari Californiat 2017')
	AddTextEntry('macla', 'Mercedes Class A')
	AddTextEntry('mlbrabus', 'Mercedes Brabus')
	AddTextEntry('rs7r', 'Audi RS7-R ABT')
	AddTextEntry('divo', 'Bugatti Divo')
	AddTextEntry('tmax', 'Yamaha T-Max')
	AddTextEntry('urus2018', 'Lamborghini Urus 2018')
	AddTextEntry('ghispo2', 'maseratiPOLICE')
	AddTextEntry('rs318', 'Audi RS3')
	AddTextEntry('terzo', 'Lamborghini-Terzo')
	AddTextEntry('gtr', 'Nissan GTR')
	AddTextEntry('q820', 'Audi Q8')
	AddTextEntry('brabus700', 'Brabus X6 700')
	AddTextEntry('g770', 'Lumma G770')
	AddTextEntry('r820', 'Audi R820')
	AddTextEntry('rmodlfa', 'Lexus LFA')
	AddTextEntry('2f2frx7', '1994 Mazda RX-7')
	AddTextEntry('2f2fs2000', '2001 Honda S2000')
	AddTextEntry('350zdk', '2002 Nissan 350z DK')
	AddTextEntry('350zm', '2002 Nissan 350z Morimoto')
	AddTextEntry('fnfjetta', '1995 Volkswagen Jetta')
	AddTextEntry('fnfrx7dom', '1993 Mazda RX-7')
	AddTextEntry('gle53', 'AMG GLE 53')
	AddTextEntry('CHARGERF8', 'Fast Charger')
	AddTextEntry('911turbos', '911turbos')
	AddTextEntry('AMGGTRR20', 'CoupÃ© AMG GTR 2020')
	AddTextEntry('rmodgt63', 'Mercedes-AMG GT63 S Coupe')
	AddTextEntry('r820', 'Audi R8')
	AddTextEntry('kart', 'kart')
	AddTextEntry('e63amg', 'Mercedes-Benz E 63 AMG')
	AddTextEntry('MERS63C', 'Mercedes S63 AMG')
	AddTextEntry('rmodrs6', 'Audi RS6')
	AddTextEntry('rmodrs6r', 'Audi RS6-R ABT')
	AddTextEntry('rmodjeep', 'Jeep 4x4')
	AddTextEntry('rmodbolide', '2020 Bugatti Bolide')
	AddTextEntry('rmodzl1', 'Chevrolet Camaro ZL1')
	AddTextEntry('yzfsm', 'Yamaha 450 YZF')
	AddTextEntry('rmodmi8lb', 'BMW I8')
	AddTextEntry('twingo', 'Twingo')
	AddTextEntry('a45amg', 'Mercedes-Benz A45 AMG')
	AddTextEntry('lp610', 'Lamborghini Huracan')
	AddTextEntry('lp700', 'Lamborghini Aventador')
	AddTextEntry('S63C217', 'Mercedes-AMG S63')
	AddTextEntry('rs666', 'RS 666')
	AddTextEntry('rmodbiposto', 'Abarth 695 Biposto')
	AddTextEntry('golf75r', 'Golf 7 R')
	AddTextEntry('rmodf12tdf', 'Ferrari F12 TDF')
	AddTextEntry('rmodg65', 'Mercedes G-65 AMG')
	AddTextEntry('rmoddarki8', 'BMW EVO i8')
	AddTextEntry('s1000rr', 'BMW S1000RR')
	AddTextEntry('SubaruSTI7', 'Subaru STI 7')
	AddTextEntry('rmodc63amg', 'C63 AMG')
	AddTextEntry('bmxP2', 'Bmx')
	AddTextEntry('rmodsianr', 'Lamborghini Sian R')
	AddTextEntry('rmode63s', 'Mercedes-AMG E 63 S')
	AddTextEntry('rmodlp670', 'Lamborghini Murcielago')
	AddTextEntry('rmodlp770', 'Lamborghini Centenario')
	AddTextEntry('rmodx6', 'BMW X6')
	AddTextEntry('rmodsuprapandem', 'Toyota GR Supra Pandem RB')
	AddTextEntry('rmodz350pandem', 'Nissan 350Z RB')
	AddTextEntry('rmodbugatti', 'La Voiture Noire')
	AddTextEntry('rmodrs7', 'Audi RS7 Sportback')
	AddTextEntry('dodgeems', 'Dodge EMS')
	AddTextEntry('rmodf40', 'Ferrari F40')
	AddTextEntry('ksd', 'KTM Super Duke R')
	AddTextEntry('rmod240sx', 'Nissan 240SX')
	AddTextEntry('rmodbacalar', 'Bentley Mulliner Bacalar')
	AddTextEntry('rmodrover', 'Range Rover MANSORY')
	AddTextEntry('RS7C8WB', 'Audi RS7 2NCS Wide Body')
	AddTextEntry('rmodi8ks', 'BMW I8M Liberty Walk')
	AddTextEntry('rmodrs7', 'Audi RS7')
	AddTextEntry('pmansory', 'Porsche Panamera Mansory')
	AddTextEntry('mxv450sm', 'Aprilia MXV 450')
	AddTextEntry('pstmansory', 'Porsche Cayenne Mansory')
	AddTextEntry('rmodm4gts', 'BMW M4 GTS')
	AddTextEntry('mlmansory', 'Levante Mansory')
	AddTextEntry('rmodgtr50', 'Nissan GT-R50')
	AddTextEntry('bugatti', 'Bugatti Veyron')
	AddTextEntry('velociraptor', 'Hennessey Velociraptor 6x6')
	AddTextEntry('720s', 'McLaren 720S')
	AddTextEntry('rmodlego1', 'Lego Chiron')
	AddTextEntry('rmodlego2', 'Lego F40')
	AddTextEntry('rmodlego3', 'Lego Cooper')
	AddTextEntry('rmodlegoporsche', 'Lego Porsche')
	AddTextEntry('rmodlegosenna', 'Lego Senna')
	AddTextEntry('rmodm5e34', 'Bmw M5 E34')
	AddTextEntry('450crf', 'Honda CRF 450')
	AddTextEntry('golf7gti', 'Golf 7 GTI')
	AddTextEntry('teslapd', 'Tesla PRIOR')
	AddTextEntry('RAPTOR150', 'Ford Raptor 2017')
	AddTextEntry('2019gt3rs', 'Porsche 911 GT3 RS')
	AddTextEntry('2020exc', '2020 KTM EXC450')
	AddTextEntry('rmodcharger69', 'Dodge Charger 1969')
	AddTextEntry('rmodjesko', 'Koenigsegg Jesko')
	AddTextEntry('gladiator', 'Jeep Gladiator Rubicon')
	AddTextEntry('redeye', 'Dodge Challenger Redeye')
	AddTextEntry('w140gto', 'Mercedes-Benz AMG S600')
	AddTextEntry('19raptor', 'Ford 19 Raptor')
	AddTextEntry('rmodspeed', 'McLaren Speedtail')
	AddTextEntry('rmodp1gtr', 'McLaren P1 GTR')
	AddTextEntry('ARTURA22WB', 'McLaren Artura')
	AddTextEntry('GHOSTSWB', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTEWB1', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTSWB1', 'Rolls-Royce Ghost')
	AddTextEntry('GHOSTEWB', 'Rolls-Royce Ghost')
	AddTextEntry('RS6C8', 'Audi RS6 C8')
	AddTextEntry('r8spyder20', 'Audi R8 Spyder')
	AddTextEntry('g63topcar', 'G63 INFERNO')
	AddTextEntry('por718gt4', 'Porsche 718 Cayman GT4')
	AddTextEntry('roma20', '2020 Ferrari Roma')
	AddTextEntry('porto18', '2018 Ferrari Portofino')
	AddTextEntry('rs520', 'Audi RS5 Coupe')
	AddTextEntry('rs6rabt20', 'Audi RS6-R ABT')
	AddTextEntry('amgone', 'Mercedes AMG One')
	AddTextEntry('gle63', 'Mercedes-AMG GLE 63 S Coupe')
	AddTextEntry('gle63c', 'Lumma CLR G 800')
	AddTextEntry('gle53', 'Mercedes-AMG GLE 53')
	AddTextEntry('rmodporsche918', 'Porsche 918 Widebody')
	AddTextEntry('rmodsennagtr', 'McLaren Senna GTR')
	AddTextEntry('rmodm4', 'BMW M4')
	AddTextEntry('rmodr8c', 'Audi R8 Sypeder')
	AddTextEntry('rmodrs6police', 'Audi RS6 Police')
	AddTextEntry('s65amg', 'Mercedes-Benz S65 AMG')
	AddTextEntry('gls600', 'Mercedes-Maybach GLS 600')
	AddTextEntry('gls20', 'Mercedes-AMG GLS 63 2020')
	AddTextEntry('gls63_de_dmz', 'Mercedes-AMG GLS 63 Renforce') --MEILLEUR !!!!!!!!!!!!!!!!!!!!--
	AddTextEntry('g632019', 'Mercedes-AMG G 63 2019')
	AddTextEntry('amggt320', 'Mercedes-AMG GT 320')
	AddTextEntry('amggtbs', 'Mercedes-AMG GT Black Series')
	AddTextEntry('amggtr', 'Mercedes-AMG GT R')
	AddTextEntry('amggtsprior', 'Mercedes-AMG GT S Prior-Design')
	AddTextEntry('brabus500', 'BRABUS Mercedes G500 4x4')
	AddTextEntry('BRABUS700', 'Brabus 700 6x6')
	AddTextEntry('brabuse700', 'Brabus 700')
	AddTextEntry('cbr1000rrr', 'Honda CBR1000RR-R')
	AddTextEntry('g650', 'Mercedes-Maybach G 650')
	AddTextEntry('rmodsupra', 'Toyota Supra')
	AddTextEntry('911gt3r', 'Porsche 911 GT3 R')
	AddTextEntry('800pro', 'JetSki')
	AddTextEntry('rs7c821', '2021 Audi RS7 Sportback')
	AddTextEntry('polmav2', 'Police Maverick')
	AddTextEntry('mh65c', 'HH-65 Dolphin')
end)