--╔════════════════════════════════════════════════════════════════════════════════╗

-- ██████╗ ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗███████╗
-- ██╔══██╗██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝██╔════╝
-- ██████╔╝██║██║        ██║   ██║   ██║██████╔╝█████╗  ███████╗
-- ██╔═══╝ ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝  ╚════██║
-- ██║     ██║╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗███████║
-- ╚═╝     ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝
                                                             

Config.Pictures = {
    -- cash
    ['cash'] = 'assets/images/items/money.png',
    ['dirtycash'] = 'assets/images/items/money.png',
    -- id card
    ['id'] = 'assets/images/items/id_card.png',
    ['weapon'] = 'assets/images/items/weaponlicense.png',
    ['drive'] = 'assets/images/items/driver_license.png',
    ['police'] = 'assets/images/items/badge-lspd2.png',
    ['id_card_f'] = 'assets/images/items/securitycard_green.png',
    -- food
    ['water'] = 'assets/images/items/water.png',
    ['coca'] = 'assets/images/items/coca.png',
    ['burger'] = 'assets/images/items/burger.png',
    ['burgerclassique'] = 'assets/images/items/burger.png',
    ['beer'] = 'assets/images/items/beer.png',
    ['tomato'] = 'assets/images/items/tomato.png',
    ['whisky'] = 'assets/images/items/whisky.png',
    ['cafe'] = 'assets/images/items/cafe.png',
    ['bread'] = 'assets/images/items/bread.png',
    ['vodka'] = 'assets/images/items/vodka.png',
    ['vine'] = 'assets/images/items/vinewoodrose.png',

    ['brochet'] = 'assets/images/items/brochet.png',
    ['cabillaud'] = 'assets/images/items/cabillaud.png',
    ['cofee'] = 'assets/images/items/caffe.png',
    ['coke'] = 'assets/images/items/coke.png',
    ['donuts'] = 'assets/images/items/strawdonut.png',
    ['limonade'] = 'assets/images/items/cool_lime_refresha.png',
    ['mojito'] = 'assets/images/items/mojito.png',
    ['olive'] = 'assets/images/items/olives.png',
    ['coke_pooch'] = 'assets/images/items/coke_pooch.png',
    ['meth_pooch'] = 'assets/images/items/meth_pooch.png',
    ['weed_pooch'] = 'assets/images/items/weed_pooch.png',
    ['sardine'] = 'assets/images/items/sardine.png',
    ['saumon'] = 'assets/images/items/saumon.png',
    ['tabac'] = 'assets/images/items/tabac.png', 
    ['tabacbrun'] = 'assets/images/items/tabacbrun.png',
    ['thon'] = 'assets/images/items/thon.png',
    ['truite'] = 'assets/images/items/truite.png',
    ['viande_1'] = 'assets/images/items/viande_1.png',
    ['viande_2'] = 'assets/images/items/viande_2.png',
    ['cacahuete'] = 'assets/images/items/cacahuete.png',
    ['casino_chips'] = 'assets/images/items/chips.png',
    ['fanta'] = 'assets/images/items/fanta.png',
    ['icetea'] = 'assets/images/items/icetea.png',
    ['wiskycoca'] = 'assets/images/items/wiskycoca.png',
    ['grapperaisin'] = 'assets/images/items/grapperaisin.png',
    ['cornichons'] = 'assets/images/items/cornichons.png',
    ['salade'] = 'assets/images/items/Salade.png',
    ['tomates'] = 'assets/images/items/tomates.png',
    ['steak'] = 'assets/images/items/steak.png',
    ['painburger'] = 'assets/images/items/painburger.png',
    ['frites'] = 'assets/images/items/frites.png',
    ['orangina'] = 'assets/images/items/orangina.png',

    -- drugs
    ['weed'] = 'assets/images/items/weed.png',
    ['weed_packaged'] = 'assets/images/items/weed_packaged.png',
    ['cocaine'] = 'assets/images/items/cocaine.png',
    ['cocaine_packaged'] = 'assets/images/items/cocaine_packaged.png',
    ['meth'] = 'assets/images/items/meth.png',
    ['meth_packaged'] = 'assets/images/items/meth_packaged.png',
    -- objets
    ['armor'] = 'assets/images/items/armor.png',
    ['bandage'] = 'assets/images/items/bandage.png',
    ['bankcard'] = 'assets/images/items/bankcard.png',
    ['bag'] = 'assets/images/items/bag.png',
    ['phone'] = 'assets/images/items/classic_phone.png',
    ['bijoux'] = 'assets/images/items/jewels.png',
    ['jewels'] = 'assets/images/items/jewels.png',
    ['radio'] = 'assets/images/items/radio.png',
    ['fixkit'] = 'assets/images/items/fixkit.png',
    ['computercrack'] = 'assets/images/items/computercrack.png',
    ['jumelle'] = 'assets/images/items/jumelle.png',
    ['medikit'] = 'assets/images/items/medikit.png',
    ['boombox'] = 'assets/images/items/boombox.png',
    ['kevlarlow'] = 'assets/images/items/kevlar.png',
    ['kevlarmid'] = 'assets/images/items/kevlar.png',
    ['kevlar'] = 'assets/images/items/kevlar.png',
    ['fishingrod'] = 'assets/images/items/fishingrod.png',
    ['bitcoin'] = 'assets/images/items/bitcoin.png',
    -- clothe
    ['pants'] = 'assets/images/items/jean.png',
    ['top'] = 'assets/images/items/shirt.png',
    ['shoes'] = 'assets/images/items/shoes.png',
    ['helmet'] = 'assets/images/items/hat.png',
    ['glasses'] = 'assets/images/items/tie.png',
    ['outfit'] = 'assets/images/items/tenue.png',
    ['mask'] = 'assets/images/items/mask.png',
    ['bags'] = 'assets/images/items/sac.png',
    ['watches'] = 'assets/images/items/montre.png',
    ['ears'] = 'assets/images/items/oreille.png',
    ['chain'] = 'assets/images/items/chaine.png',
    -- rcore camping
    -- ['gazebo_3'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160538212007986/gazebo_3.png',
    -- ['gazebo_1'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160539793281084/gazebo_1.png',
    -- ['gazebo_2'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160540170747945/gazebo_2.png',
    -- ['chair_3'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160539264782457/chair_3.png',
    -- ['chair_2'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160538795016293/chair_2.png',
    -- ['chair_1'] = 'https://cdn.discordapp.com/attachments/1121826470797529178/1129160538493030550/chair_1.png',
    -- ['tent_2'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129160960171585628/tent_2.png',
    -- ['tent_1'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129160960632963192/tent_1.png',
    -- ['wood'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129160993541460108/wood.png',
    -- ['beerkeg'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129161032632377515/beerkeg.png',
    -- ['raw_chicken'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129161292037488691/raw_chicken.png',
    -- ['cooked_chicken'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129162470775345284/cooked_chicken.png',
    -- ['fireplace'] = 'https://cdn.discordapp.com/attachments/1008837979894198413/1129161605658185738/fireplace.png',
    -- weapon
    ['clip'] = 'assets/images/items/clip.png',
    --Meele
    ['WEAPON_DAGGER'] = "assets/images/weapons/meele/weapon_dagger.png",
    ['WEAPON_BAT'] = "assets/images/weapons/meele/weapon_bat.png",
    ['WEAPON_BOTTLE'] = "assets/images/weapons/meele/weapon_bottle.png",
    ['WEAPON_CROWBAR'] = "assets/images/weapons/meele/weapon_crowbar.png",
    ['WEAPON_FLASHLIGHT'] = "assets/images/weapons/meele/weapon_flashlight.png",
    ['WEAPON_GOLFCLUB'] = "assets/images/weapons/meele/weapon_golfclub.png",
    ['WEAPON_HAMMER'] = "assets/images/weapons/meele/weapon_hammer.png",
    ['WEAPON_HATCHET'] = "assets/images/weapons/meele/weapon_hatchet.png",
    ['WEAPON_KNUCKLE'] = "assets/images/weapons/meele/weapon_knuckle.png",
    ['WEAPON_KNIFE'] = "assets/images/weapons/meele/weapon_knife.png",
    ['WEAPON_MACHETE'] = "assets/images/weapons/meele/weapon_machete.png",
    ['WEAPON_SWITCHBLADE'] = "assets/images/weapons/meele/weapon_switchblade.png",
    ['WEAPON_NIGHTSTICK'] = "assets/images/weapons/meele/weapon_nightstick.png",
    ['WEAPON_WRENCH'] = "assets/images/weapons/meele/weapon_wrench.png",
    ['WEAPON_BATTLEAXE'] = "assets/images/weapons/meele/weapon_battleaxe.png",
    ['WEAPON_POOLCUE'] = "assets/images/weapons/meele/weapon_poolcue.png",
    ['WEAPON_STONE_HATCHET'] = "assets/images/weapons/meele/weapon_stone_hatchet.png",
    --Handgun
    ['WEAPON_PISTOL'] = "assets/images/weapons/handguns/weapon_pistol.png",
    ['WEAPON_PISTOL_MK2'] = "assets/images/weapons/handguns/weapon_pistol_mk2.png",
    ['WEAPON_COMBATPISTOL'] = "assets/images/weapons/handguns/weapon_combatpistol.png",
    ['WEAPON_APPISTOL'] = "assets/images/weapons/handguns/weapon_appistol.png",
    ['WEAPON_STUNGUN'] = "assets/images/weapons/handguns/weapon_stungun.png",
    ['WEAPON_PISTOL50'] = "assets/images/weapons/handguns/weapon_pistol50.png",
    ['WEAPON_SNSPISTOL'] = "assets/images/weapons/handguns/weapon_snspistol.png",
    ['WEAPON_SNSPISTOL_MK2'] = "assets/images/weapons/handguns/weapon_snspistol_mk2.png",
    ['WEAPON_HEAVYPISTOL'] = "assets/images/weapons/handguns/weapon_heavypistol.png",
    ['WEAPON_VINTAGEPISTOL'] = "assets/images/weapons/handguns/weapon_vintagepistol.png",
    ['WEAPON_FLAREGUN'] = "assets/images/weapons/handguns/weapon_flaregun.png",
    ['WEAPON_MARKSMANPISTOL'] = "assets/images/weapons/handguns/weapon_marksmanpistol.png",
    ['WEAPON_REVOLVER'] = "assets/images/weapons/handguns/weapon_revolver.png",
    ['WEAPON_REVOLVER_MK2'] = "assets/images/weapons/handguns/weapon_revolver_mk2.png",
    ['WEAPON_DOUBLEACTION'] = "assets/images/weapons/handguns/weapon_doubleaction.png",
    ['WEAPON_RAYPISTOL'] = "assets/images/weapons/handguns/weapon_raypistol.png",
    ['WEAPON_CERAMICPISTOL'] = "assets/images/weapons/handguns/weapon_ceramicpistol.png",
    ['WEAPON_NAVYREVOLVER'] = "assets/images/weapons/handguns/weapon_navyrevolver.png",
    ['WEAPON_GADGETPISTOL'] = "assets/images/weapons/handguns/weapon_gadgetpistol.png",
    ['WEAPON_STUNGUN_MP'] = "assets/images/weapons/handguns/weapon_stungun.png",
    --Submachine
    ['WEAPON_MICROSMG'] = "assets/images/weapons/submachine/weapon_microsmg.png",
    ['WEAPON_SMG'] = "assets/images/weapons/submachine/weapon_smg.png",
    ['WEAPON_SMG_MK2'] = "assets/images/weapons/submachine/weapon_smg_mk2.png",
    ['WEAPON_ASSAULTSMG'] = "assets/images/weapons/submachine/weapon_assaultsmg.png",
    ['WEAPON_COMBATPDW'] = "assets/images/weapons/submachine/weapon_combatpdw.png",
    ['WEAPON_MACHINEPISTOL'] = "assets/images/weapons/submachine/weapon_machinepistol.png",
    ['WEAPON_MINISMG'] = "assets/images/weapons/submachine/weapon_minismg.png",
    ['WEAPON_RAYCARBINE'] = "assets/images/weapons/submachine/weapon_raycarbine.png",
    --Shotguns
    ['WEAPON_PUMPSHOTGUN'] = "assets/images/weapons/shotguns/weapon_pumpshotgun.png",
    ['WEAPON_PUMPSHOTGUN_MK2'] = "assets/images/weapons/shotguns/weapon_pumpshotgun_mk2.png",
    ['WEAPON_SAWNOFFSHOTGUN'] = "assets/images/weapons/shotguns/weapon_sawnoffshotgun.png",
    ['WEAPON_ASSAULTSHOTGUN'] = "assets/images/weapons/shotguns/weapon_assaultshotgun.png",
    ['WEAPON_BULLPUPSHOTGUN'] = "assets/images/weapons/shotguns/weapon_bullpupshotgun.png",
    ['WEAPON_MUSKET'] = "assets/images/weapons/shotguns/weapon_musket.png",
    ['WEAPON_HEAVYSHOTGUN'] = "assets/images/weapons/shotguns/weapon_heavyshotgun.png",
    ['WEAPON_DBSHOTGUN'] = "assets/images/weapons/shotguns/weapon_dbshotgun.png",
    ['WEAPON_AUTOSHOTGUN'] = "assets/images/weapons/shotguns/weapon_autoshotgun.png",
    ['WEAPON_COMBATSHOTGUN'] = "assets/images/weapons/shotguns/weapon_combatshotgun.png",
    --Assault Rifles
    ['WEAPON_ASSAULTRIFLE'] = "assets/images/weapons/rifles/weapon_assaultrifle.png",
    ['WEAPON_ASSAULTRIFLE_MK2'] = "assets/images/weapons/rifles/weapon_assaultrifle_mk2.png",
    ['WEAPON_CARBINERIFLE'] = "assets/images/weapons/rifles/weapon_carbinerifle.png",
    ['WEAPON_CARBINERIFLE_MK2'] = "assets/images/weapons/rifles/weapon_carbinerifle_mk2.png",
    ['WEAPON_ADVANCEDRIFLE'] = "assets/images/weapons/rifles/weapon_advancedrifle.png",
    ['WEAPON_SPECIALCARBINE'] = "assets/images/weapons/rifles/weapon_specialcarbine.png",
    ['WEAPON_SPECIALCARBINE_MK2'] = "assets/images/weapons/rifles/weapon_specialcarbine_mk2.png",
    ['WEAPON_BULLPUPRIFLE'] = "assets/images/weapons/rifles/weapon_bullpuprifle.png",
    ['WEAPON_BULLPUPRIFLE_MK2'] = "assets/images/weapons/rifles/weapon_bullpuprifle_mk2.png",
    ['WEAPON_COMPACTRIFLE'] = "assets/images/weapons/rifles/weapon_compactrifle.png",
    ['WEAPON_MILITARYRIFLE'] = "assets/images/weapons/rifles/weapon_militaryrifle.png",
    ['WEAPON_HEAVYRIFLE'] = "assets/images/weapons/rifles/weapon_heavyrifle.png",
    --Light Machine
    ['WEAPON_MG'] = "assets/images/weapons/lightmachine/weapon_mg.png",
    ['WEAPON_COMBATMG'] = "assets/images/weapons/lightmachine/weapon_combatmg.png",
    ['WEAPON_COMBATMG_MK2'] = "assets/images/weapons/lightmachine/weapon_combatmg_mk2.png",
    ['WEAPON_GUSENBERG'] = "assets/images/weapons/lightmachine/weapon_gusenberg.png",
    --Sniper
    ['WEAPON_SNIPERRIFLE'] = "assets/images/weapons/sniper/weapon_sniperrifle.png",
    ['WEAPON_HEAVYSNIPER'] = "assets/images/weapons/sniper/weapon_heavysniper.png",
    ['WEAPON_HEAVYSNIPER_MK2'] = "assets/images/weapons/sniper/weapon_heavysniper_mk2.png",
    ['WEAPON_MARKSMANRIFLE'] = "assets/images/weapons/sniper/weapon_marksmanrifle.png",
    ['WEAPON_MARKSMANRIFLE_MK2'] = "assets/images/weapons/sniper/weapon_marksmanrifle_mk2.png",
    ['WEAPON_PRECISIONRIFLE'] = "assets/images/weapons/sniper/weapon_precisionrifle.png",
    --Heavy Weapons
    ['WEAPON_RPG'] = "assets/images/weapons/heavy/weapon_rpg.png",
    ['WEAPON_GRENADELAUNCHER'] = "assets/images/weapons/heavy/weapon_grenadelauncher.png",
    ['WEAPON_GRENADELAUNCHER_SMOKE'] = "assets/images/weapons/heavy/weapon_grenadelauncher.png",
    ['WEAPON_MINIGUN'] = "assets/images/weapons/heavy/weapon_minigun.png",
    ['WEAPON_FIREWORK'] = "assets/images/weapons/heavy/weapon_firework.png",
    ['WEAPON_RAILGUN'] = "assets/images/weapons/heavy/weapon_railgun.png",
    ['WEAPON_HOMINGLAUNCHER'] = "assets/images/weapons/heavy/weapon_hominglauncher.png",
    ['WEAPON_COMPACTLAUNCHER'] = "assets/images/weapons/heavy/weapon_compactlauncher.png",
    ['WEAPON_RAYMINIGUN'] = "assets/images/weapons/heavy/weapon_rayminigun.png",
    ['WEAPON_EMPLAUNCHER'] = "assets/images/weapons/heavy/weapon_emplauncher.png",
    --Throwables
    ['WEAPON_GRENADE'] = "assets/images/weapons/throwables/weapon_grenade.png",
    ['WEAPON_BZGAS'] = "assets/images/weapons/throwables/weapon_gas.png",
    ['WEAPON_MOLOTOV'] = "assets/images/weapons/throwables/weapon_molotov.png",
    ['WEAPON_STICKYBOMB'] = "assets/images/weapons/throwables/weapon_stickybomb.png",
    ['WEAPON_PROXMINE'] = "assets/images/weapons/throwables/weapon_proxmine.png",
    ['WEAPON_SNOWBALL'] = "assets/images/weapons/throwables/weapon_snowball.png",
    ['WEAPON_PIPEBOMB'] = "assets/images/weapons/throwables/weapon_pipebomb.png",
    ['WEAPON_BALL'] = "assets/images/weapons/throwables/weapon_ball.png",
    ['WEAPON_SMOKEGRENADE'] = "assets/images/weapons/throwables/weapon_gas.png",
    ['WEAPON_FLARE'] = "assets/images/weapons/throwables/weapon_flare.png",
    --Miscellaneous
    ['WEAPON_PETROLCAN'] = "assets/images/weapons/miscellaneous/weapon_petrolcan.png",
    ['GADGET_PARACHUTE'] = "assets/images/weapons/miscellaneous/gadget_parachute.png",
    ['WEAPON_FIREEXTINGUISHER'] = "assets/images/weapons/miscellaneous/weapon_fireextinguisher.png",
    ['WEAPON_HAZARDCAN'] = "assets/images/weapons/miscellaneous/weapon_hazardcan.png",
    --Add on
    ['WEAPON_KATANA4'] = "assets/images/weapons/addon/weapon_katana4.png",
    ['WEAPON_KATANA3'] = "assets/images/weapons/addon/weapon_katana3.png",
    ['WEAPON_KATANA2'] = "assets/images/weapons/addon/weapon_katana2.png",
    ['WEAPON_KATANA'] = "assets/images/weapons/addon/weapon_katana.png",
    ['WEAPON_PENETRATOR'] = "assets/images/weapons/addon/weapon_penetrator.png",
}

--╚════════════════════════════════════════════════════════════════════════════════╝