Config = {}
Config.Locale = 'fr'

Config.DefaultGroup = 'user'
Config.DefaultLevel = '0'
Config.CommandPrefix = '/'
Config.DefaultPosition = vector3(-666.22, 581.5, 140.57)
Config.DefaultIdentifier = "license";

Config.DEVMODE = false; ---#vCore3 WRAPPER (EPROTECT)

Config.PlayerAllowedForDanger = {
	["license:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"] = true, -- iZeyy
	["license:111d41054afb4f409a45b38a9b4e3146fecb8fe2"] = true, -- Zxnka
	["license:4d0fab85aa287ec29da0ad1479f38ab3d029579b"] = true, -- SneaX
}

Config.Accounts = {
	['cash'] = {
		label = _U('cash'),
		starting = 0,
		priority = 1
	},
	['dirtycash'] = {
		label = _U('dirtycash'),
		starting = 0,
		priority = 2
	},
	['bank'] = {
		label = _U('bank'),
		starting = 0,
		priority = 3
	},
	['crypto'] = {
		label = 'Crypto',
		starting = 0,
		priority = 4
	},
	['chip'] = {
		label = 'Jetons Casino',
		starting = 0,
		priority = 4
	}
}

Config.EnableSocietyPayouts = true
Config.PaycheckInterval = 45 * 60 * 1000
Config.MaxWeight = 45

Config.BlacklistedWeapons = {

	'WEAPON_RPG',
	'WEAPON_RAYPISTOl',
	'WEAPON_RAYCARBINE',
	'WEAPON_AUTOSHOTGUN',
	--'WEAPON_DBSHOTGUN',
	'WEAPON_GRENADELAUNCHER',
	'WEAPON_GRENADELAUNCHER_SMOKE',
	'WEAPON_MINIGUN',
	'WEAPON_FIREWORK',
	'WEAPON_RAILGUN',
	'WEAPON_HOMINGLAUNCHER',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_RAYMINIGUN',
	'WEAPON_BZGAS',
	'WEAPON_GRENADE',
	'WEAPON_MOLOTOV',
	'WEAPON_STICKYBOMB',
	'WEAPON_PROXMINE',
	'WEAPON_PIPEBOMB',
	'WEAPON_SMOKEGRENADE',

};

Config.BlacklistedVehicles = {

	'sunrise1',
	'tug',
	'avisa',
	'dinghy5',
	'kosatka',
	'patrolboat',
	'cerberus',
	'deluxo',
	'cerberus2',
	'cerberus3',
	'hauler',
	'hauler2',
	'phantom2',
	'stockade3',
	'terbyte',
	'issi6',
	'issi5',
	'issi4',
	'riot2',
	'akula',
	'annihilator',
	'annihilator2',
	'buzzard',
	'cargobob',
	'cargobob3',
	'cargobob4',
	'hunter',
	'savage',
	'skylift',
	'valkyrie',
	'valkyrie2',
	'bulldozer',
	'cutter',
	'dump',
	'handler',
	'apc',
	'barrage',
	'chernobog',
	'halftrack',
	'khanjali',
	'minitank',
	'rhino',
	'scarab',
	'scarab2',
	'scarab3',
	'thruster',
	'trailersmall2',
	'oppressor',
	'oppressor2',
	'blazer5',
	'schafter6',
	'schafter5',
	'baller5',
	'tampa3',
	'boxville5',
	'ruiner2',
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'kuruma2',
	'brutus2',
	'brutus3',
	'dune3',
	'dune4',
	'dune5',
	'insurgent',
	'insurgent3',
	'marshall',
	'monster',
	'monster3',
	'monster4',
	'monster5',
	'menacer',
	'nightshark',
	'technical',
	'technical2',
	'technical3',
	'zhaba',
	'avenger2',
	'besra',
	'blimp',
	'blimp2',
	'blimp3',
	'bombushka',
	'cargoplane',
	'hydra',
	'jet',
	'lazer',
	'molotok',
	'nokota',
	'pyro',
	'rogue',
	'starling',
	'strikeforce',
	'titan',
	'volatol',
	'alkonost',
	'baller6',
	'brickade',
	'rallytruck',
	'tourbus',
	'wastelander',
	'zr380',
	'zr3802',
	'zr3803',
	'toreador',
	'vigilante',
	'armytanker',
	'armytrailer',
	'armytrailer2',
	'baletrailer',
	'boattrailer',
	'cablecar',
	'docktrailer',
	'freighttrailer',
	'graintrailer',
	'proptrailer',
	'raketrailer',
	'tr2',
	'tr3',
	'tr4',
	'trflat',
	'tvtrailer',
	'tanker',
	'tanker2',
	'trailerlarge',
	'trailerlogs',
	'trailersmall',
	'trailers',
	'trailers2',
	'trailers3',
	'trailers4',
	'freight',
	'freightcar',
	'freightcont1',
	'freightcont2',
	'freightgrain',
	'metrotrain',
	'tankercar',
	'voltic2',
	'savestra',
	'limo2',
	'scramjet',
	'slamvan6',
	'slamvan5',
	'slamvan4',
	'imperator3',
	'duke2',
	'dominator6',
	'dominator5',
	'dominator4',
	'deathbike2',
	'deathbike3',
	'deathbike',
	'submersible2',
	'submersible',
	'firetruk',
	'mixer',
	'mixer2',
	'ruiner3',
	'tula',
	'rcbandito',
	'caracara',
	'granger2',
	'champion',
	'paragon2',
	'deity',
	'jubilee',
	'stromberg',
	'havok',
	'Mogul',
	'patriot3',

};