--[[
  This file is part of Valestia RolePlay.
  Copyright (c) Valestia RolePlay - All Rights Reserved
  Unauthorized using, copying, modifying and/or distributing of this file,
  via any medium is strictly prohibited. This code is confidential.
--]]

pSocietyTranslation = {

    ['fr'] = {
        ["money_symbol"] = "$",
        ['society'] = "Entreprise",
        ['society_money'] = "Argent",
        ['withdraw_money'] = "Retirer de l'argent",
        ['deposit_money'] = "Déposer de l'argent",
        ['wash_money'] = "Blanchir de l'argent",
        ['manage_employees'] = "Gestion des employés",
        ['manage_salary'] = "Gestion des salaires",
        ['search'] = "Rechercher",
        ['list'] = "Liste",
        ["choose"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Choisir →",
        ["current"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Actuel",
        ["kick_society"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Expulser de l'entreprise",
        ["sure"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Êtes-vous vraiment sûre ?~s~",
        ["yes"] = "oui",
        ["how_much"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Combien ?",
        ["impossible_action"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous ne possédez pas cette somme d'argent",
        ["recruit"] = "Recruter",
        ["recruit_desc"] = "Permet de recruter le joueur le plus proche.",
        ["wash_money_desc"] = "Convertie l'argent sale en argent propre",
        ["manage_salary_desc"] = "Les salaires sont tirés du compte de l'entreprise !",
        ["withdrew"] = "Vous avez retiré~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~",
        ["deposed"] = "Vous avez déposé~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~",
        ["washed"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous avez blanchis",
        ["modified_profession"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Profession modifiée !",
        ["profession_evolved"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Votre profession à évoluée",
        ["cannot_assign_profession"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous ne pouvez pas attribuer cette profession !",
        ["request_sent"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Demande envoyée.",
        ["press_interact"] = "Appuyez sur ~INPUT_PICKUP~ pour interagir",
        ["new_offer"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Nouvelle offre.",
        ["accept"] = "Accepter",
        ["decline"] = "Décliner",
        ["job"] = "Emploie",
        ["accepted_offer"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous avez accepté l'offre",
        ["decline_offer"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous avez décliner l'offre",
        ["ignored_offer"] = "~HUD_COLOUR_PM_WEAPONS_PURCHASABLE~Vous avez ignoré l'offre",
        ["log_action"] = "Action",
        ["log_company"] = "Entreprise :",
        ["log_withdrew"] = "Le joueur a retiré",
        ["log_deposed"] = "Le joueur a déposé",
        ["log_washed"] = "Le joueur a blanchis",
        ["log_setjob"] = "Le joueur à modifié la profession de",
        ["log_recruit"] = "Le joueur à été recruté par"
    },

    ['en'] = {
        ["money_symbol"] = "",
        ['society'] = "",
        ['society_money'] = "",
        ['withdraw_money'] = "",
        ['deposit_money'] = "",
        ['wash_money'] = "",
        ['manage_employees'] = "",
        ['manage_salary'] = "",
        ['search'] = "",
        ['list'] = "",
        ["choose"] = "",
        ["current"] = "",
        ["kick_society"] = "",
        ["sure"] = "",
        ["yes"] = "",
        ["how_much"] = "",
        ["impossible_action"] = "",
        ["recruit"] = "",
        ["recruit_desc"] = "",
        ["wash_money_desc"] = "",
        ["manage_salary_desc"] = "",
        ["withdrew"] = "",
        ["deposed"] = "",
        ["washed"] = "",
        ["modified_profession"] = "",
        ["profession_evolved"] = "",
        ["cannot_assign_profession"] = "",
        ["request_sent"] = "",
        ["press_interact"] = "",
        ["new_offer"] = "",
        ["accept"] = "",
        ["decline"] = "",
        ["job"] = "",
        ["accepted_offer"] = "",
        ["decline_offer"] = "",
        ["ignored_offer"] = "",
        ["log_action"] = "",
        ["log_company"] = "",
        ["log_withdrew"] = "",
        ["log_deposed"] = "",
        ["log_washed"] = "",
        ["log_setjob"] = "",
    },
}