---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@type table
RageUIv1 = {}

---@type table
RMenuv1 = setmetatable({}, RMenuv1)

---@type table
local TotalMenus = {}

---Add
---@param Type string
---@param Name string
---@param Menu table
---@return _G
---@public
function RMenuv1.Add(Type, Name, Menu)
    if RMenuv1[Type] ~= nil then
        RMenuv1[Type][Name] = {
            Menu = Menu
        }
    else
        RMenuv1[Type] = {}
        RMenuv1[Type][Name] = {
            Menu = Menu
        }
    end
    
    table.insert(TotalMenus, Menu)
end

---Get
---@param Type string
---@param Name string
---@return table
---@public
function RMenuv1:Get(Type, Name)
    if self[Type] ~= nil and self[Type][Name] ~= nil then
        return self[Type][Name].Menu
    end
end

---GetType
---@param Type string
---@return table
---@public
function RMenuv1:GetType(Type)
    if self[Type] ~= nil then
        return self[Type]
    end
end

---Settings
---@param Type string
---@param Name string
---@param Settings string
---@param Value any optional
---@return void
---@public
function RMenuv1:Settings(Type, Name, Settings, Value)
    if Value ~= nil then
        self[Type][Name][Settings] = Value
    else
        return self[Type][Name][Settings]
    end
end


---Delete
---@param Type string
---@param Name string
---@return void
---@public
function RMenuv1:Delete(Type, Name)
    self[Type][Name] = nil
    collectgarbage()
end

---DeleteType
---@param Type string
---@return void
---@public
function RMenuv1:DeleteType(Type)
    self[Type] = nil
    collectgarbage()
end
