ConfigPNJ = {
    RelationshipGroups = {
        `AGGRESSIVE_INVESTIGATE`,
        `AMBIENT_GANG_BALLAS`,
        `AMBIENT_GANG_CULT`,
        `AMBIENT_GANG_FAMILY`,
        `AMBIENT_GANG_HILLBILLY`,
        `AMBIENT_GANG_LOST`,
        `AMBIENT_GANG_MARABUNTE`,
        `AMBIENT_GANG_MEXICAN`,
        `AMBIENT_GANG_SALVA`,
        `AMBIENT_GANG_WEICHENG`,
        `ARMY`,
        `CAT`,
        `CIVFEMALE`,
        `CIVMALE`,
        `COP`,
        --`COUGAR`,
        `DEALER`,
        `DEER`,
        `DOMESTIC_ANIMAL`,
        `FIREMAN`,
        `GANG_1`,
        `GANG_2`,
        `GANG_9`,
        `GANG_10`,
        `GUARD_DOG`,
        `HATES_PLAYER`,
        `HEN`,
        `MEDIC`,
        `MISSION2`,
        `MISSION3`,
        `MISSION4`,
        `MISSION5`,
        `MISSION6`,
        `MISSION7`,
        `MISSION8`,
        `NO_RELATIONSHIP`,
        `PLAYER`,
        `PRISONER`,
        `PRIVATE_SECURITY`,
        `SECURITY_GUARD`,
        --`SHARK`,
        `SPECIAL`,
        --`WILD_ANIMAL`,
    },
    PickupWeapons = {
        `PICKUP_AMMO_BULLET_MP`,
        `PICKUP_AMMO_FIREWORK`,
        `PICKUP_AMMO_FIREWORK_MP`,
        `PICKUP_AMMO_FLAREGUN`,
        `PICKUP_AMMO_GRENADELAUNCHER`,
        `PICKUP_AMMO_GRENADELAUNCHER_MP`,
        `PICKUP_AMMO_HOMINGLAUNCHER`,
        `PICKUP_AMMO_MG`,
        `PICKUP_AMMO_MINIGUN`,
        `PICKUP_AMMO_MISSILE_MP`,
        `PICKUP_AMMO_PISTOL`,
        `PICKUP_AMMO_RIFLE`,
        `PICKUP_AMMO_RPG`,
        `PICKUP_AMMO_SHOTGUN`,
        `PICKUP_AMMO_SMG`,
        `PICKUP_AMMO_SNIPER`,
        `PICKUP_WEAPON_ADVANCEDRIFLE`,
        `PICKUP_WEAPON_APPISTOL`,
        `PICKUP_WEAPON_ASSAULTRIFLE`,
        `PICKUP_WEAPON_ASSAULTRIFLE_MK2`,
        `PICKUP_WEAPON_ASSAULTSHOTGUN`,
        `PICKUP_WEAPON_ASSAULTSMG`,
        `PICKUP_WEAPON_AUTOSHOTGUN`,
        `PICKUP_WEAPON_BAT`,
        `PICKUP_WEAPON_BATTLEAXE`,
        `PICKUP_WEAPON_BOTTLE`,
        `PICKUP_WEAPON_BULLPUPRIFLE`,
        `PICKUP_WEAPON_BULLPUPRIFLE_MK2`,
        `PICKUP_WEAPON_BULLPUPSHOTGUN`,
        `PICKUP_WEAPON_CARBINERIFLE`,
        `PICKUP_WEAPON_CARBINERIFLE_MK2`,
        `PICKUP_WEAPON_COMBATMG`,
        `PICKUP_WEAPON_COMBATMG_MK2`,
        `PICKUP_WEAPON_COMBATPDW`,
        `PICKUP_WEAPON_COMBATPISTOL`,
        `PICKUP_WEAPON_COMPACTLAUNCHER`,
        `PICKUP_WEAPON_COMPACTRIFLE`,
        `PICKUP_WEAPON_CROWBAR`,
        `PICKUP_WEAPON_DAGGER`,
        `PICKUP_WEAPON_DBSHOTGUN`,
        `PICKUP_WEAPON_DOUBLEACTION`,
        `PICKUP_WEAPON_FIREWORK`,
        `PICKUP_WEAPON_FLAREGUN`,
        `PICKUP_WEAPON_FLASHLIGHT`,
        `PICKUP_WEAPON_GRENADE`,
        `PICKUP_WEAPON_GRENADELAUNCHER`,
        `PICKUP_WEAPON_GUSENBERG`,
        `PICKUP_WEAPON_GolfClub`,
        `PICKUP_WEAPON_HAMMER`,
        `PICKUP_WEAPON_HATCHET`,
        `PICKUP_WEAPON_HEAVYPISTOL`,
        `PICKUP_WEAPON_HEAVYSHOTGUN`,
        `PICKUP_WEAPON_HEAVYSNIPER`,
        `PICKUP_WEAPON_HEAVYSNIPER_MK2`,
        `PICKUP_WEAPON_HOMINGLAUNCHER`,
        `PICKUP_WEAPON_KNIFE`,
        `PICKUP_WEAPON_KNUCKLE`,
        `PICKUP_WEAPON_MACHETE`,
        `PICKUP_WEAPON_MACHINEPISTOL`,
        `PICKUP_WEAPON_MARKSMANPISTOL`,
        `PICKUP_WEAPON_MARKSMANRIFLE`,
        `PICKUP_WEAPON_MARKSMANRIFLE_MK2`,
        `PICKUP_WEAPON_MG`,
        `PICKUP_WEAPON_MICROSMG`,
        `PICKUP_WEAPON_MINIGUN`,
        `PICKUP_WEAPON_MINISMG`,
        `PICKUP_WEAPON_MOLOTOV`,
        `PICKUP_WEAPON_MUSKET`,
        `PICKUP_WEAPON_NIGHTSTICK`,
        `PICKUP_WEAPON_PETROLCAN`,
        `PICKUP_WEAPON_PIPEBOMB`,
        `PICKUP_WEAPON_PISTOL`,
        `PICKUP_WEAPON_PISTOL50`,
        `PICKUP_WEAPON_PISTOL_MK2`,
        `PICKUP_WEAPON_POOLCUE`,
        `PICKUP_WEAPON_PROXMINE`,
        `PICKUP_WEAPON_PUMPSHOTGUN`,
        `PICKUP_WEAPON_PUMPSHOTGUN_MK2`,
        `PICKUP_WEAPON_RAILGUN`,
        `PICKUP_WEAPON_RAYCARBINE`,
        `PICKUP_WEAPON_RAYMINIGUN`,
        `PICKUP_WEAPON_RAYPISTOL`,
        `PICKUP_WEAPON_REVOLVER`,
        `PICKUP_WEAPON_REVOLVER_MK2`,
        `PICKUP_WEAPON_RPG`,
        `PICKUP_WEAPON_SAWNOFFSHOTGUN`,
        `PICKUP_WEAPON_SMG`,
        `PICKUP_WEAPON_SMG_MK2`,
        `PICKUP_WEAPON_SMOKEGRENADE`,
        `PICKUP_WEAPON_SNIPERRIFLE`,
        `PICKUP_WEAPON_SNSPISTOL`,
        `PICKUP_WEAPON_SNSPISTOL_MK2`,
        `PICKUP_WEAPON_SPECIALCARBINE`,
        `PICKUP_WEAPON_SPECIALCARBINE_MK2`,
        `PICKUP_WEAPON_STICKYBOMB`,
        `PICKUP_WEAPON_STONE_HATCHET`,
        `PICKUP_WEAPON_STUNGUN`,
        `PICKUP_WEAPON_SWITCHBLADE`,
        `PICKUP_WEAPON_VINTAGEPISTOL`,
        `PICKUP_WEAPON_WRENCH`,
    },
    SuppressedVehiclesModels = {
        -- Tankers
        `armytanker`,
        `tanker`,
        `tanker2`,
        -- Military
        `apc`,
        `barracks`,
        `barracks2`,
        `barracks3`,
        `barrage`,
        `chernobog`,
        `crusader`,
        `halftrack`,
        `khanjali`,
        `minitank`,
        `rhino`,
        `scarab`,
        `scarab2`,
        `scarab3`,
        `thruster`,
        `trailersmall2`,
        -- Helico
        `polmav`,
        `akula`,
        `annihilator`,
        `buzzard`,
        `buzzard2`,
        `cargobob`,
        `cargobob2`,
        `cargobob3`,
        `cargobob4`,
        `frogger`,
        `frogger2`,
        `havok`,
        `hunter`,
        `maverick`,
        `savage`,
        `seasparrow`,
        `skylift`,
        `supervolito`,
        `supervolito2`,
        `swift`,
        `swift2`,
        `valkyrie`,
        `valkyrie2`,
        `volatus`,
        -- planes
        `alphaz1`,
        `avenger`,
        `avenger2`,
        `besra`,
        `blimp`,
        `blimp2`,
        `blimp3`,
        `bombushka`,
        `cargoplane`,
        `cuban800`,
        `dodo`,
        `duster`,
        `howard`,
        `hydra`,
        `jet`,
        `lazer`,
        `luxor`,
        `luxor2`,
        `mammatus`,
        `microlight`,
        `miljet`,
        `mogul`,
        `molotok`,
        `nimbus`,
        `nokota`,
        `pyro`,
        `rogue`,
        `seabreeze`,
        `shamal`,
        `starling`,
        `strikeforce`,
        `stunt`,
        `titan`,
        `tula`,
        `velum`,
        `velum2`,
        `vestra`,
        `volatol`,
    },
    SuppressedPedsModels = {
        --`a_c_mtlion`,
        `a_c_cormorant`,
        `a_c_pigeon`,
        `a_c_chickenhawk`,
        `a_c_crow`,
        `a_c_seagull`,
    },

    RemoveHudCommonents = {
        [1] = true, --WANTED_STARS,
        [2] = true, --WEAPON_ICON
        [3] = true, --CASH
        [4] = true,  --MP_CASH
        [5] = true, --MP_MESSAGE
        [6] = true, --VEHICLE_NAME
        [7] = true,-- AREA_NAME
        [8] = true,-- VEHICLE_CLASS
        [9] = true, --STREET_NAME
        [10] = false, --HELP_TEXT
        [11] = false, --FLOATING_HELP_TEXT_1
        [12] = false, --FLOATING_HELP_TEXT_2
        [13] = true, --CASH_CHANGE
        [14] = false, --RETICLE
        [15] = false, --SUBTITLE_TEXT
        [16] = false, --RADIO_STATIONS
        [17] = false, --SAVING_GAME,
        [18] = true, --GAME_STREAM
        [19] = true, --WEAPON_WHEEL
        [20] = true, --WEAPON_WHEEL_STATS
        [21] = true, --HUD_COMPONENTS
        [22] = true, --HUD_WEAPONS
    }
}