---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0.25, Width = 431, Height = 42 },
}

---@type Panel
function RageUIv3.RenderSprite(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUIv3.ItemOffset + (RageUIv3.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end


---@type Panel
function RageUIv3.RenderWeapons(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 370, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end
---@type Panel
function RageUIv3.CaissePreviewOpen(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUIv3.ItemOffset + (RageUIv3.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end
---@type Panel
function RageUIv3.RenderCaisse(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 300.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function RageUIv3.RenderCaissePreview(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 530.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function RageUIv3.RenderJournalier(Dictionary, Texture)
    local CurrentMenu = RageUIv3.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 400.25, TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 20255, 0, 0, 255, 255, 255);
            RageUIv3.StatisticPanelCount = RageUIv3.StatisticPanelCount + 1
        end
    end
end

local BoxSettings = {
    itemPerLine = 4,
    width = 215,
    height = 120,
    space = 5
}

function RageUIv3.RenderBox(Items)
    local lastLine = 0;
    for k, v in pairs(VisualitionCaisse[Items]) do
        local x = 525 + (((k -1) - (BoxSettings.itemPerLine * lastLine)) * (BoxSettings.width + BoxSettings.space))
        local y = (lastLine * (BoxSettings.height + BoxSettings.space))
        RenderSprite("caissemystere", v.model, x, y, BoxSettings.width, BoxSettings.height, 0, 255, 255, 255, 255)
        if math.tointeger(k / BoxSettings.itemPerLine) ~= nil then
            lastLine = math.tointeger(k / BoxSettings.itemPerLine)
        end
    end
end