---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 21/04/2019 21:20
---

---round
---@param num number
---@param numDecimalPlaces number
---@return number
---@public
function math.round(num, numDecimalPlaces)
    return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

---starts
---@param String string
---@param Start number
---@return number
---@public
function string.starts(String, Start)
    return string.sub(String, 1, string.len(Start)) == Start
end

---@type table
RageUIPolice.Menus = setmetatable({}, RageUIPolice.Menus)

---@type table
---@return boolean
RageUIPolice.Menus.__call = function()
    return true
end

---@type table
RageUIPolice.Menus.__index = RageUIPolice.Menus

---@type table
RageUIPolice.CurrentMenu = nil

---@type table
RageUIPolice.NextMenu = nil

---@type number
RageUIPolice.Options = 0

---@type number
RageUIPolice.ItemOffset = 0

---@type number
RageUIPolice.StatisticPanelCount = 0

---@type table
RageUIPolice.UI = {
    Current = "RageUIPolice",
    Style = {
        RageUIPolice = {
            Width = 0
        },
        NativeUI = {
            Width = 0
        }
    }
}

---@type table
RageUIPolice.Settings = {
    Debug = false,
    Controls = {
        Up = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 172 },
                { 1, 172 },
                { 2, 172 },
                { 0, 241 },
                { 1, 241 },
                { 2, 241 },
            },
        },
        Down = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 173 },
                { 1, 173 },
                { 2, 173 },
                { 0, 242 },
                { 1, 242 },
                { 2, 242 },
            },
        },
        Left = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        Right = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        SliderLeft = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        SliderRight = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        Select = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 201 },
                { 1, 201 },
                { 2, 201 },
            },
        },
        Back = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 177 },
                { 1, 177 },
                { 2, 177 },
                { 0, 199 },
                { 1, 199 },
                { 2, 199 },
            },
        },
        Click = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 24 },
            },
        },
        Enabled = {
            Controller = {
                { 0, 2 }, -- Look Up and Down
                { 0, 1 }, -- Look Left and Right
                { 0, 25 }, -- Aim
                { 0, 24 }, -- Attack
            },
            Keyboard = {
                { 0, 201 }, -- Select
                { 0, 195 }, -- X axis
                { 0, 196 }, -- Y axis
                { 0, 187 }, -- Down
                { 0, 188 }, -- Up
                { 0, 189 }, -- Left
                { 0, 190 }, -- Right
                { 0, 202 }, -- Back
                { 0, 217 }, -- Select
                { 0, 242 }, -- Scroll down
                { 0, 241 }, -- Scroll up
                { 0, 239 }, -- Cursor X
                { 0, 240 }, -- Cursor Y
                { 0, 31 }, -- Move Up and Down
                { 0, 30 }, -- Move Left and Right
                { 0, 21 }, -- Sprint
                { 0, 22 }, -- Jump
                { 0, 23 }, -- Enter
                { 0, 75 }, -- Exit Vehicle
                { 0, 71 }, -- Accelerate Vehicle
                { 0, 72 }, -- Vehicle Brake
                { 0, 59 }, -- Move Vehicle Left and Right
                { 0, 89 }, -- Fly Yaw Left
                { 0, 9 }, -- Fly Left and Right
                { 0, 8 }, -- Fly Up and Down
                { 0, 90 }, -- Fly Yaw Right
                { 0, 76 }, -- Vehicle Handbrake
            },
        },
    },
    Audio = {
        Id = nil,
        Use = "RageUIPolice",
        RageUIPolice = {
            UpDown = {
                audioName = "HUD_FREEMODE_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        },
        NativeUI = {
            UpDown = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        }
    },
    Items = {
        Title = {
            Background = { Width = 431, Height = 107 },
            Text = { X = 215, Y = 20, Scale = 1.15 },
        },
        Subtitle = {
            Background = { Width = 431, Height = 37 },
            Text = { X = 8, Y = 3, Scale = 0.35 },
            PreText = { X = 425, Y = 3, Scale = 0.35 },
        },
        Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0, Width = 431 },
        Navigation = {
            Rectangle = { Width = 431, Height = 18 },
            Offset = 5,
            Arrows = { Dictionary = "commonmenu", Texture = "shop_arrows_upanddown", X = 190, Y = -6, Width = 50, Height = 50 },
        },
        Description = {
            Bar = { Y = 4, Width = 431, Height = 4 },
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 30 },
            Text = { X = 8, Y = 10, Scale = 0.35 },
        },
    },
    Panels = {
        Grid = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 275 },
            Grid = { Dictionary = "pause_menu_pages_char_mom_dad", Texture = "nose_grid", X = 115.5, Y = 47.5, Width = 200, Height = 200 },
            Circle = { Dictionary = "mpinventory", Texture = "in_world_circle", X = 115.5, Y = 47.5, Width = 20, Height = 20 },
            Text = {
                Top = { X = 215.5, Y = 15, Scale = 0.35 },
                Bottom = { X = 215.5, Y = 250, Scale = 0.35 },
                Left = { X = 57.75, Y = 130, Scale = 0.35 },
                Right = { X = 373.25, Y = 130, Scale = 0.35 },
            },
        },
        Percentage = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 76 },
            Bar = { X = 9, Y = 50, Width = 413, Height = 10 },
            Text = {
                Left = { X = 25, Y = 15, Scale = 0.35 },
                Middle = { X = 215.5, Y = 15, Scale = 0.35 },
                Right = { X = 398, Y = 15, Scale = 0.35 },
            },
        },
    },
}

function RageUIPolice.SetScaleformParams(scaleform, data)
    data = data or {}
    for k, v in pairs(data) do
        PushScaleformMovieFunction(scaleform, v.name)
        if v.param then
            for _, par in pairs(v.param) do
                if math.type(par) == "integer" then
                    PushScaleformMovieFunctionParameterInt(par)
                elseif type(par) == "boolean" then
                    PushScaleformMovieFunctionParameterBool(par)
                elseif math.type(par) == "float" then
                    PushScaleformMovieFunctionParameterFloat(par)
                elseif type(par) == "string" then
                    PushScaleformMovieFunctionParameterString(par)
                end
            end
        end
        if v.func then
            v.func()
        end
        PopScaleformMovieFunctionVoid()
    end
end

---Visible
---@param Menu function
---@param Value boolean
---@return table
---@public
function RageUIPolice.Visible(Menu, Value)
    if Menu ~= nil then
        if Menu() then
            if type(Value) == "boolean" then
                if Value then
                    if RageUIPolice.CurrentMenu ~= nil then
			if RageUIPolice.CurrentMenu.Closed ~= nil then
                            RageUIPolice.CurrentMenu.Closed()
                        end
                        RageUIPolice.CurrentMenu.Open = not Value
                    end
                    Menu:UpdateInstructionalButtons(Value);
                    Menu:UpdateCursorStyle();
                    RageUIPolice.CurrentMenu = Menu
                    menuOpen = true
                else
                    menuOpen = false
                    RageUIPolice.CurrentMenu = nil
                end
                Menu.Open = Value
                RageUIPolice.Options = 0
                RageUIPolice.ItemOffset = 0
                RageUIPolice.LastControl = false
            else
                return Menu.Open
            end
        end
    end
end

function RageUIPolice.CloseAll()
    menuOpen = false
    if RageUIPolice.CurrentMenu ~= nil then
        local parent = RageUIPolice.CurrentMenu.Parent
        while parent ~= nil do
            parent.Index = 1
            parent.Pagination.Minimum = 1
            parent.Pagination.Maximum = 10
            parent = parent.Parent
        end
        RageUIPolice.CurrentMenu.Index = 1
        RageUIPolice.CurrentMenu.Pagination.Minimum = 1
        RageUIPolice.CurrentMenu.Pagination.Maximum = 10
        RageUIPolice.CurrentMenu.Open = false
        RageUIPolice.CurrentMenu = nil
    end
    RageUIPolice.Options = 0
    RageUIPolice.ItemOffset = 0
    ResetScriptGfxAlign()
end

---Banner
---@return nil
---@public
---@param Enabled boolean
function RageUIPolice.Banner(Enabled, Glare)
    if type(Enabled) == "boolean" then
        if Enabled == true then


            if RageUIPolice.CurrentMenu ~= nil then
                if RageUIPolice.CurrentMenu() then


                    RageUIPolice.ItemsSafeZone(RageUIPolice.CurrentMenu)

                    if RageUIPolice.CurrentMenu.Sprite then
                        RenderSprite(RageUIPolice.CurrentMenu.Sprite.Dictionary, RageUIPolice.CurrentMenu.Sprite.Texture, RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y, RageUIPolice.Settings.Items.Title.Background.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.Settings.Items.Title.Background.Height, nil)
                    else
                        RenderRectangle(RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y, RageUIPolice.Settings.Items.Title.Background.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.Settings.Items.Title.Background.Height, RageUIPolice.CurrentMenu.Rectangle.R, RageUIPolice.CurrentMenu.Rectangle.G, RageUIPolice.CurrentMenu.Rectangle.B, RageUIPolice.CurrentMenu.Rectangle.A)
                    end

                    RenderText(RageUIPolice.CurrentMenu.Title, RageUIPolice.CurrentMenu.X + RageUIPolice.Settings.Items.Title.Text.X + (RageUIPolice.CurrentMenu.WidthOffset / 2), RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Title.Text.Y, 1, RageUIPolice.Settings.Items.Title.Text.Scale, 255, 255, 255, 255, 1)
                    RageUIPolice.ItemOffset = RageUIPolice.ItemOffset + RageUIPolice.Settings.Items.Title.Background.Height
                end
            end
        end
    else
        error("Enabled is not boolean")
    end
end

---CloseAll -- TODO 
---@return nil
---@public
-- function RageUIPolice:CloseAll()
--     RageUIPolice.PlaySound(RageUIPolice.Settings.Audio.Library, RageUIPolice.Settings.Audio.Back)
--     RageUIPolice.NextMenu = nil
--     RageUIPolice.Visible(RageUIPolice.CurrentMenu, false)
-- end

---Subtitle
---@return nil
---@public
function RageUIPolice.Subtitle()
    if RageUIPolice.CurrentMenu ~= nil then
        if RageUIPolice.CurrentMenu() then
            RageUIPolice.ItemsSafeZone(RageUIPolice.CurrentMenu)
            if RageUIPolice.CurrentMenu.Subtitle ~= "" then
                RenderRectangle(RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.ItemOffset, RageUIPolice.Settings.Items.Subtitle.Background.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.Settings.Items.Subtitle.Background.Height + RageUIPolice.CurrentMenu.SubtitleHeight, 0, 0, 0, 255)
                RenderText(RageUIPolice.CurrentMenu.Subtitle, RageUIPolice.CurrentMenu.X + RageUIPolice.Settings.Items.Subtitle.Text.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Subtitle.Text.Y + RageUIPolice.ItemOffset, 0, RageUIPolice.Settings.Items.Subtitle.Text.Scale, 245, 245, 245, 255, nil, false, false, RageUIPolice.Settings.Items.Subtitle.Background.Width + RageUIPolice.CurrentMenu.WidthOffset)
                if RageUIPolice.CurrentMenu.Index > RageUIPolice.CurrentMenu.Options or RageUIPolice.CurrentMenu.Index < 0 then
                    RageUIPolice.CurrentMenu.Index = 1
                end
                RageUIPolice.RefreshPagination()
                if RageUIPolice.CurrentMenu.PageCounter == nil then
                    RenderText(RageUIPolice.CurrentMenu.PageCounterColour .. RageUIPolice.CurrentMenu.Index .. " / " .. RageUIPolice.CurrentMenu.Options, RageUIPolice.CurrentMenu.X + RageUIPolice.Settings.Items.Subtitle.PreText.X + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Subtitle.PreText.Y + RageUIPolice.ItemOffset, 0, RageUIPolice.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                else
                    RenderText(RageUIPolice.CurrentMenu.PageCounter, RageUIPolice.CurrentMenu.X + RageUIPolice.Settings.Items.Subtitle.PreText.X + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Subtitle.PreText.Y + RageUIPolice.ItemOffset, 0, RageUIPolice.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                end
                RageUIPolice.ItemOffset = RageUIPolice.ItemOffset + RageUIPolice.Settings.Items.Subtitle.Background.Height
            end
        end
    end
end

---Background
---@return nil
---@public
function RageUIPolice.Background()
    if RageUIPolice.CurrentMenu ~= nil then
        if RageUIPolice.CurrentMenu() then
            RageUIPolice.ItemsSafeZone(RageUIPolice.CurrentMenu)
            SetScriptGfxDrawOrder(0)
            RenderSprite(RageUIPolice.Settings.Items.Background.Dictionary, RageUIPolice.Settings.Items.Background.Texture, RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Background.Y + RageUIPolice.CurrentMenu.SubtitleHeight, RageUIPolice.Settings.Items.Background.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.ItemOffset, 0, 0, 0, 0, 255)
            SetScriptGfxDrawOrder(1)
        end
    end
end

---Description
---@return nil
---@public
function RageUIPolice.Description()
    if RageUIPolice.CurrentMenu ~= nil and RageUIPolice.CurrentMenu.Description ~= nil then
        if RageUIPolice.CurrentMenu() then
            RageUIPolice.ItemsSafeZone(RageUIPolice.CurrentMenu)
            RenderRectangle(RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Description.Bar.Y + RageUIPolice.CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, RageUIPolice.Settings.Items.Description.Bar.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.Settings.Items.Description.Bar.Height, 0, 0, 0, 255)
            RenderSprite(RageUIPolice.Settings.Items.Description.Background.Dictionary, RageUIPolice.Settings.Items.Description.Background.Texture, RageUIPolice.CurrentMenu.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Description.Background.Y + RageUIPolice.CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, RageUIPolice.Settings.Items.Description.Background.Width + RageUIPolice.CurrentMenu.WidthOffset, RageUIPolice.CurrentMenu.DescriptionHeight, 0, 0, 0, 255)
            RenderText(RageUIPolice.CurrentMenu.Description, RageUIPolice.CurrentMenu.X + RageUIPolice.Settings.Items.Description.Text.X, RageUIPolice.CurrentMenu.Y + RageUIPolice.Settings.Items.Description.Text.Y + RageUIPolice.CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, 0, RageUIPolice.Settings.Items.Description.Text.Scale, 255, 255, 255, 255, nil, false, false, RageUIPolice.Settings.Items.Description.Background.Width + RageUIPolice.CurrentMenu.WidthOffset - 8.0)
            RageUIPolice.ItemOffset = RageUIPolice.ItemOffset + RageUIPolice.CurrentMenu.DescriptionHeight + RageUIPolice.Settings.Items.Description.Bar.Y
        end
    end
end

---Render
---@param instructionalButton boolean
---@return nil
---@public
function RageUIPolice.Render(instructionalButton)
    if RageUIPolice.CurrentMenu ~= nil then
        if RageUIPolice.CurrentMenu() then
            if RageUIPolice.CurrentMenu.Safezone then
                ResetScriptGfxAlign()
            end
            if (instructionalButton) then
                DrawScaleformMovieFullscreen(RageUIPolice.CurrentMenu.InstructionalScaleform, 255, 255, 255, 255, 0)
            end
            RageUIPolice.CurrentMenu.Options = RageUIPolice.Options
            RageUIPolice.CurrentMenu.SafeZoneSize = nil
            RageUIPolice.Controls()
            RageUIPolice.Options = 0
            RageUIPolice.StatisticPanelCount = 0
            RageUIPolice.ItemOffset = 0
            if RageUIPolice.CurrentMenu.Controls.Back.Enabled and RageUIPolice.CurrentMenu.Closable then
                if RageUIPolice.CurrentMenu.Controls.Back.Pressed then
                    RageUIPolice.CurrentMenu.Controls.Back.Pressed = false
                    local Audio = RageUIPolice.Settings.Audio
                    RageUIPolice.PlaySound(Audio[Audio.Use].Back.audioName, Audio[Audio.Use].Back.audioRef)
                    collectgarbage()
                    if RageUIPolice.CurrentMenu.Closed ~= nil then
                        RageUIPolice.CurrentMenu.Closed()
                    end
                    if RageUIPolice.CurrentMenu.Parent ~= nil then
                        if RageUIPolice.CurrentMenu.Parent() then
                            RageUIPolice.NextMenu = RageUIPolice.CurrentMenu.Parent
                            RageUIPolice.CurrentMenu:UpdateCursorStyle()
                        else
                            --print('xxx') Debug print
                            RageUIPolice.NextMenu = nil
                            RageUIPolice.Visible(RageUIPolice.CurrentMenu, false)
                        end
                    else
                        --print('zz') Debug print
                        RageUIPolice.NextMenu = nil
                        RageUIPolice.Visible(RageUIPolice.CurrentMenu, false)
                    end
                end
            end
            if RageUIPolice.NextMenu ~= nil then
                if RageUIPolice.NextMenu() then
                    RageUIPolice.Visible(RageUIPolice.CurrentMenu, false)
                    RageUIPolice.Visible(RageUIPolice.NextMenu, true)
                    RageUIPolice.CurrentMenu.Controls.Select.Active = false
                    RageUIPolice.NextMenu = nil
                    RageUIPolice.LastControl = false
                end
            end
        end
    end
end

---ItemsDescription
---@param CurrentMenu table
---@param Description string
---@param Selected boolean
---@return nil
---@public
function RageUIPolice.ItemsDescription(CurrentMenu, Description, Selected)
    ---@type table
    if Description ~= "" or Description ~= nil then
        local SettingsDescription = RageUIPolice.Settings.Items.Description;
        if Selected and CurrentMenu.Description ~= Description then
            CurrentMenu.Description = Description or nil
            ---@type number
            local DescriptionLineCount = GetLineCount(CurrentMenu.Description, CurrentMenu.X + SettingsDescription.Text.X, CurrentMenu.Y + SettingsDescription.Text.Y + CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, 0, SettingsDescription.Text.Scale, 255, 255, 255, 255, nil, false, false, SettingsDescription.Background.Width + (CurrentMenu.WidthOffset - 5.0))
            if DescriptionLineCount > 1 then
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height * DescriptionLineCount
            else
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height + 7
            end
        end
    end
end

---MouseBounds
---@param CurrentMenu table
---@param Selected boolean
---@param Option number
---@param SettingsButton table
---@return boolean
---@public
function RageUIPolice.ItemsMouseBounds(CurrentMenu, Selected, Option, SettingsButton)
    ---@type boolean
    local Hovered = false
    Hovered = RageUIPolice.IsMouseInBounds(CurrentMenu.X + CurrentMenu.SafeZoneSize.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SafeZoneSize.Y + CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height)
    if Hovered and not Selected then
        RenderRectangle(CurrentMenu.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SubtitleHeight + RageUIPolice.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height, 255, 255, 255, 20)
        if CurrentMenu.Controls.Click.Active then
            CurrentMenu.Index = Option
            local Audio = RageUIPolice.Settings.Audio
            RageUIPolice.PlaySound(Audio[Audio.Use].Error.audioName, Audio[Audio.Use].Error.audioRef)
        end
    end
    return Hovered;
end

---ItemsSafeZone
---@param CurrentMenu table
---@return nil
---@public
function RageUIPolice.ItemsSafeZone(CurrentMenu)
    if not CurrentMenu.SafeZoneSize then
        CurrentMenu.SafeZoneSize = { X = 0, Y = 0 }
        if CurrentMenu.Safezone then
            CurrentMenu.SafeZoneSize = RageUIPolice.GetSafeZoneBounds()
            SetScriptGfxAlign(76, 84)
            SetScriptGfxAlignParams(0, 0, 0, 0)
        end
    end
end

function RageUIPolice.CurrentIsEqualTo(Current, To, Style, DefaultStyle)
    if (Current == To) then
        return Style;
    else
        return DefaultStyle or {};
    end
end

function RageUIPolice.RefreshPagination()
    if (RageUIPolice.CurrentMenu ~= nil) then
        if (RageUIPolice.CurrentMenu.Index > 10) then
            local offset = RageUIPolice.CurrentMenu.Index - 10
            RageUIPolice.CurrentMenu.Pagination.Minimum = 1 + offset
            RageUIPolice.CurrentMenu.Pagination.Maximum = 10 + offset
        else
            RageUIPolice.CurrentMenu.Pagination.Minimum = 1
            RageUIPolice.CurrentMenu.Pagination.Maximum = 10
        end
    end
end

function RageUIPolice.IsVisible(menu, header, glare, instructional, items, panels)
    if (RageUIPolice.Visible(menu)) then
        if (header == true) then
            RageUIPolice.Banner(true, glare or false)
        end
        RageUIPolice.Subtitle()
        if (items ~= nil) then
            items()
        end
        RageUIPolice.Background();
        RageUIPolice.Navigation();
        RageUIPolice.Description();
        if (panels ~= nil) then
            panels()
        end
        RageUIPolice.Render(instructional or false)
    end
end


---CreateWhile
---@param wait number
---@param menu table
---@param key number
---@param closure function
---@return void
---@public
function RageUIPolice.CreateWhile(wait, menu, key, closure)
    Citizen.CreateThread(function()
        while (true) do
            Citizen.Wait(wait or 0.1)

            if (key ~= nil) then
                if IsControlJustPressed(1, key) then
                    RageUIPolice.Visible(menu, not RageUIPolice.Visible(menu))
                end
            end

            closure()
        end
    end)
end

---SetStyleAudio
---@param StyleAudio string
---@return void
---@public
function RageUIPolice.SetStyleAudio(StyleAudio)
    RageUIPolice.Settings.Audio.Use = StyleAudio or "RageUIPolice"
end

function RageUIPolice.GetStyleAudio()
    return RageUIPolice.Settings.Audio.Use or "RageUIPolice"
end

