Config["SheriffJob"] = {}

Config["SheriffJob"]["Fine"] = {
	{label = 'Usage abusif du klaxon', price = 200},
	{label = 'Franchir une ligne continue', price = 50},
	{label = 'Circulation à contresens', price = 150},
	{label = 'Demi-tour non autorisé', price = 100},
	{label = 'Circulation hors-route', price = 250},
	{label = 'Stationnement gênant / interdit', price = 200},
	{label = 'Non-respect d\'un stop', price = 100},
	{label = 'Véhicule non en état', price = 500},
	{label = 'Conduite sans permis', price = 700},
	{label = 'Délit de fuite', price = 4200},
	{label = 'Excès de vitesse < 5 kmh', price = 625},
	{label = 'Excès de vitesse 5-15 kmh', price = 1250},
	{label = 'Excès de vitesse 15-30 kmh', price = 1875},
	{label = 'Excès de vitesse > 30 kmh', price = 2500},
	{label = 'Dégradation de la voie publique', price = 3750},
	{label = 'Trouble à l\'ordre publique', price = 3750},
	{label = 'Entrave opération de police', price = 7500},
	{label = 'Insulte envers / entre civils', price = 1250},
	{label = 'Menace verbale envers civil', price = 5000},
	{label = 'Menace verbale envers policier', price = 7500},
	{label = 'Manifestation illégale', price = 6250},
	{label = 'Tentative de corruption', price = 2500},
	{label = 'Arme blanche sortie en ville', price = 10000},
	{label = 'Arme léthale sortie en ville', price = 25000},
	{label = 'Port d\'arme illégal', price = 50000},
	{label = 'Pris en flag lockpick', price = 2500},
	{label = 'Vol de voiture', price = 3750},
	{label = 'Vente de drogue', price = 37500},
	{label = 'Fabrication de drogue', price = 50000},
	{label = 'Possession de drogue', price = 30000},
	{label = 'Prise d\'ôtage civil', price = 41250},
	{label = 'Prise d\'ôtage agent de l\'état', price = 62500},
	{label = 'Braquage supérette', price = 20000},
	{label = 'Braquage de banque', price = 50000},
	{label = 'Tir sur civil', price = 50000},
	{label = 'Tir sur agent de l\'état', price = 62500},
	{label = 'Tentative de meurtre sur civil', price = 50000},
	{label = 'Tentative de meurtre sur agent', price = 62500},
	{label = 'Meurtre sur civil', price = 62500},
	{label = 'Meurte sur agent de l\'état', price = 75000},
}

Config["SheriffJob"]["MaxProps"] = 14

Config["SheriffJob"]["BossAction"] = vector3(-433.8543, 6006.866, 36.99566)
Config["SheriffJob"]["Armory"] = vector3(-448.8716, 6014.549, 36.99567)
Config["SheriffJob"]["Garage"] = vector3(-465.9149, 6003.333, 31.48919)
Config["SheriffJob"]["Cloakroom"] = vector3(-438.9184, 6008.409, 36.99566)
Config["SheriffJob"]["SeizedTrunk"] = vector3(-445.8732, 6018.722, 32.28872)
Config["SheriffJob"]["GarageSpawn"] = vector3(-470.1879, 6011.097, 31.3404)
Config["SheriffJob"]["GarageHeading"] = 313.88
Config["SheriffJob"]["DeleteCar"] = vector3(-481.987, 6024.247, 31.34039)
Config["SheriffJob"]["CellZone"] = vector3(-445.5869, 6015.086, 27.58151)
Config["SheriffJob"]["CellRadius"] = 30
Config["SheriffJob"]["CellEnd"] = vector3(-443.0804, 6015.627, 32.28868)

Config["SheriffJob"]["SeizedTrunkAcess"] = 5

Config["SheriffJob"]["ArmoryWeapon"] = {
	{label = "Tazer", weapon = "weapon_stungun", grade = 0},
	{label = "Lampe torche", weapon = "weapon_flashlight", grade = 0},
	{label = "Matraque", weapon = "weapon_nightstick", grade = 0},
	{label = "Pistolet de combat", weapon = "weapon_combatpistol", grade = 1},
	{label = "Antidote Gazeuse", weapon = "weapon_antidote", grade = 2},
	{label = "Gazeuse", weapon = "weapon_pepperspray", grade = 2},
	{label = "Megaphone", weapon = "weapon_megaphone", grade = 3},
	{label = "Carabine d'assault", weapon = "weapon_carbinerifle", grade = 6},
    {label = "Fusil à pompe", weapon = "weapon_pumpshotgun", grade = 4},
}

Config["SheriffJob"]["CellTimeMin"] = 5
Config["SheriffJob"]["CellTimeMax"] = 15

Config["SheriffJob"]["Cell"] = {
	{label = "Cellule #1", position = vector3(-446.8428, 6012.338, 27.58149)},
	{label = "Cellule #2", position = vector3(-450.0996, 6015.163, 27.5815)},
	{label = "Cellule #3", position = vector3(-445.9742, 6019.606, 27.58148)},
	{label = "Cellule #4", position = vector3(-442.8928, 6016.596, 27.5815)},
}

Config["SheriffJob"]["GarageVehicle"] = {
	{label = "Declasse Granger 550x", vehicle = "POLALAMOR", grade = 0},
    {label = "Cheval Fugitive", vehicle = "POLFUGITIVER", grade = 0},
    {label = "Bravado Buffalo", vehicle = "POLBUFFALOR2", grade = 1},
    {label = "Bradvado AWD", vehicle = "POLGRESLEYR", grade = 1},
    {label = "Vapid Cruiser", vehicle = "POLSTANIERR", grade = 2},
    {label = "Bravado Bison", vehicle = "POLBISONR", grade = 2},
    {label = "Vapid Cruiser2", vehicle = "POLTORENCER", grade = 3},
    {label = "Vapid Scout", vehicle = "POLSCOUTR", grade = 3},
    {label = "Felon Banalisé", vehicle = "policefelon", grade = 3},
    {label = "Dundreary Landstalker XL", vehicle = "polstalkerr", grade = 4},
    {label = "Vapid Caracara", vehicle = "POLCARAR", grade = 4},
    {label = "Declasse Alamo", vehicle = "POLALAMOR2", grade = 5},
    {label = "Vapid Speedo", vehicle = "POLSPEEDOR", grade = 5},
    {label = "Bravado Buffalo STX", vehicle = "POLBUFFALOR", grade = 6},
    {label = "Buffalo STX", vehicle = "lspdbuffalostxum", grade = 7},
    {label = "Vapid Explorer", vehicle = "LSPDumkscoutgnd", grade = 7},
    {label = "Lenco BearCat", vehicle = "bear01", grade = 7},
    {label = "Invetero Coquette", vehicle = "POLCOQUETTER", grade = 7},
}

Config["SheriffJob"]["Uniform"] = {
	deputy = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 0,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 0,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    deputyone = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 0,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 0,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    deputytwo = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 8,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 8,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    deputythree = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 9,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 9,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    sergent = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    sergenttwo = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    sergentchief = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 8, ['decals_2'] = 10,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    captain = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 7,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 7,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
    },
    commander = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 8,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 8,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },	
    },
    undersheriff = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 11,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 11,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },	
    },
    boss = {
        male = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 12,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 65, ['tshirt_2'] = 0,
            ['torso_1'] = 31, ['torso_2'] = 3,
            ['decals_1'] = 9, ['decals_2'] = 12,
            ['bproof_1'] = 14,  ['bproof_2'] = 0,
            ['arms'] = 12,
            ['pants_1'] = 20, ['pants_2'] = 12,
            ['shoes_1'] = 21, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = -1, ['mask_2'] = 0,
            ['bags_1'] = 11, ['bags_2'] = 0,
            ['chain_1'] = 8, ['chain_2'] = 0,
            ['ears_1'] = -1, ['ears_2'] = 0,
        },	
    },
    bullet = {
        male = {
            ['bproof_1'] = 25,  ['bproof_2'] = 2,
        },
        female = {
            ['bproof_1'] = 25,  ['bproof_2'] = 2
        }
    },
    gilet = {
        male = {
            ['bproof_1'] = 34,  ['bproof_2'] = 3,
        },
        female = {
            ['bproof_1'] = 34,  ['bproof_2'] = 3
        }
    },
	ungilet = {
		male = {
			['bproof_1'] = 14,  ['bproof_2'] = 0,
		},
		female = {
			['bproof_1'] = 14,  ['bproof_2'] = 0
		}
	},
}