Config["WeaponAnimation"] = {}

Config["WeaponAnimation"]["WeaponList"] = {
    [GetHashKey("WEAPON_UNARMED")] = {settings = {animation = true, bag = false}}, 
    [GetHashKey("WEAPON_KNIFE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_NIGHTSTICK")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_HAMMER")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_BAT")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_CROWBAR")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_GOLFCLUB")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_BOTTLE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_DAGGER")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_HATCHET")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_KNUCKLE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_MACHETE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_FLASHLIGHT")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_SWITCHBLADE")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_BATTLEAXE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_POOLCUE")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_WRENCH")] = {settings = {animation = true, bag = false}},

	[GetHashKey("WEAPON_PISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_PISTOL_MK2")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_COMBATPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_PISTOL50")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_SNSPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_SNSPISTOL_MK2")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_HEAVYPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_VINTAGEPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_MARKSMANPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_REVOLVER")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_REVOLVER_MK2")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_DOUBLEACTION")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_APPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_STUNGUN")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_FLAREGUN")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_CERAMICPISTOL")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_NAVYREVOLVER")] = {settings = {animation = true, bag = false}},
	[GetHashKey("WEAPON_GADGETPISTOL")] = {settings = {animation = true, bag = false}},

	[GetHashKey("WEAPON_MICROSMG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MACHINEPISTOL")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MINISMG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_SMG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_SMG_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_ASSAULTSMG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_COMBATPDW")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_COMBATMG")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_COMBATMG_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_GUSENBERG")] = {settings = {animation = true, bag = true}},

	[GetHashKey("WEAPON_ASSAULTRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_ASSAULTRIFLE_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_CARBINERIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_CARBINERIFLE_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_ADVANCEDRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_SPECIALCARBINE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_SPECIALCARBINE_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_BULLPUPRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_BULLPUPRIFLE_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_COMPACTRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MILITARYRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_HEAVYRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_TACTICALRIFLE")] = {settings = {animation = true, bag = true}},

	[GetHashKey("WEAPON_PUMPSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_SAWNOFFSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_BULLPUPSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_ASSAULTSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MUSKET")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_HEAVYSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_DBSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_AUTOSHOTGUN")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_COMBATSHOTGUN")] = {settings = {animation = true, bag = true}},

	[GetHashKey("WEAPON_SNIPERRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_HEAVYSNIPER")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_HEAVYSNIPER_MK2")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MARKSMANRIFLE")] = {settings = {animation = true, bag = true}},
	[GetHashKey("WEAPON_MARKSMANRIFLE_MK2")] = {settings = {animation = true, bag = true}},

	[GetHashKey("WEAPON_GRENADELAUNCHER")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_RPG")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_STINGER")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_MINIGUN")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_FIREWORK")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_RAILGUN")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_HOMINGLAUNCHER")] = {settings = {animation = false, bag = true}},
	[GetHashKey("WEAPON_COMPACTLAUNCHER")] = {settings = {animation = false, bag = true}},

	[GetHashKey("WEAPON_GRENADE")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_STICKYBOMB")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_PROXMINE")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_SMOKEGRENADE")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_BZGAS")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_MOLOTOV")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_FIREEXTINGUISHER")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_PETROLCAN")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_BALL")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_SNOWBALL")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_FLARE")] = {settings = {animation = false, bag = false}},
	[GetHashKey("WEAPON_PIPEBOMB")] = {settings = {animation = false, bag = false}},
}

Config["WeaponAnimation"]["allowed_bags"] = {
	111,
	112,
	115,
	116,
	152,
	153,
	156,
	157,
	189,
	190,
	191
}