---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0.25, Width = 431, Height = 42 },
}

---@type Panel
function RageUI.RenderSprite(Dictionary, Texture)
    local CurrentMenu = RageUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUI.ItemOffset + (RageUI.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUI.StatisticPanelCount = RageUI.StatisticPanelCount + 1
        end
    end
end

local VehiclePanel = {
    Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0, Width = 431, Height = 42 },
}

function RageUI.RenderVehicule(Dictionary, Texture)
    local CurrentMenu = RageUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            print(CurrentMenu.Y, VehiclePanel.Background.Y, CurrentMenu.SubtitleHeight, RageUI.ItemOffset, RageUI.StatisticPanelCount * 42)
            RenderSprite(Dictionary, Texture, CurrentMenu.X + 432, CurrentMenu.Y -230 + VehiclePanel.Background.Y + CurrentMenu.SubtitleHeight + 410 + (RageUI.StatisticPanelCount * 42), VehiclePanel.Background.Width + CurrentMenu.WidthOffset, VehiclePanel.Background.Height + 200, 0, 255, 255, 255, 255);
            RageUI.StatisticPanelCount = RageUI.StatisticPanelCount + 1
        end
    end
end
