---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 21/04/2019 21:20
---

---round
---@param num number
---@param numDecimalPlaces number
---@return number
---@public
function math.round(num, numDecimalPlaces)
    return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

---starts
---@param String string
---@param Start number
---@return number
---@public
function string.starts(String, Start)
    return string.sub(String, 1, string.len(Start)) == Start
end

---@type table
RageUIjh.Menus = setmetatable({}, RageUIjh.Menus)

---@type table
---@return boolean
RageUIjh.Menus.__call = function()
    return true
end

---@type table
RageUIjh.Menus.__index = RageUIjh.Menus

---@type table
RageUIjh.CurrentMenu = nil

---@type table
RageUIjh.NextMenu = nil

---@type number
RageUIjh.Options = 0

---@type number
RageUIjh.ItemOffset = 0

---@type number
RageUIjh.StatisticPanelCount = 0

---@type table
RageUIjh.UI = {
    Current = "RageUIjh",
    Style = {
        RageUIjh = {
            Width = 0
        },
        NativeUI = {
            Width = 0
        }
    }
}

---@type table
RageUIjh.Settings = {
    Debug = false,
    Controls = {
        Up = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 172 },
                { 1, 172 },
                { 2, 172 },
                { 0, 241 },
                { 1, 241 },
                { 2, 241 },
            },
        },
        Down = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 173 },
                { 1, 173 },
                { 2, 173 },
                { 0, 242 },
                { 1, 242 },
                { 2, 242 },
            },
        },
        Left = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        Right = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        SliderLeft = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 174 },
                { 1, 174 },
                { 2, 174 },
            },
        },
        SliderRight = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 175 },
                { 1, 175 },
                { 2, 175 },
            },
        },
        Select = {
            Enabled = true,
            Pressed = false,
            Active = false,
            Keys = {
                { 0, 201 },
                { 1, 201 },
                { 2, 201 },
            },
        },
        Back = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 177 },
                { 1, 177 },
                { 2, 177 },
                { 0, 199 },
                { 1, 199 },
                { 2, 199 },
            },
        },
        Click = {
            Enabled = true,
            Active = false,
            Pressed = false,
            Keys = {
                { 0, 24 },
            },
        },
        Enabled = {
            Controller = {
                { 0, 2 }, -- Look Up and Down
                { 0, 1 }, -- Look Left and Right
                { 0, 25 }, -- Aim
                { 0, 24 }, -- Attack
            },
            Keyboard = {
                { 0, 201 }, -- Select
                { 0, 195 }, -- X axis
                { 0, 196 }, -- Y axis
                { 0, 187 }, -- Down
                { 0, 188 }, -- Up
                { 0, 189 }, -- Left
                { 0, 190 }, -- Right
                { 0, 202 }, -- Back
                { 0, 217 }, -- Select
                { 0, 242 }, -- Scroll down
                { 0, 241 }, -- Scroll up
                { 0, 239 }, -- Cursor X
                { 0, 240 }, -- Cursor Y
                { 0, 31 }, -- Move Up and Down
                { 0, 30 }, -- Move Left and Right
                { 0, 21 }, -- Sprint
                { 0, 22 }, -- Jump
                { 0, 23 }, -- Enter
                { 0, 75 }, -- Exit Vehicle
                { 0, 71 }, -- Accelerate Vehicle
                { 0, 72 }, -- Vehicle Brake
                { 0, 59 }, -- Move Vehicle Left and Right
                { 0, 89 }, -- Fly Yaw Left
                { 0, 9 }, -- Fly Left and Right
                { 0, 8 }, -- Fly Up and Down
                { 0, 90 }, -- Fly Yaw Right
                { 0, 76 }, -- Vehicle Handbrake
            },
        },
    },
    Audio = {
        Id = nil,
        Use = "RageUIjh",
        RageUIjh = {
            UpDown = {
                audioName = "HUD_FREEMODE_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        },
        NativeUI = {
            UpDown = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_UP_DOWN",
            },
            LeftRight = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "NAV_LEFT_RIGHT",
            },
            Select = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "SELECT",
            },
            Back = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "BACK",
            },
            Error = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "ERROR",
            },
            Slider = {
                audioName = "HUD_FRONTEND_DEFAULT_SOUNDSET",
                audioRef = "CONTINUOUS_SLIDER",
                Id = nil
            },
        }
    },
    Items = {
        Title = {
            Background = { Width = 431, Height = 107 },
            Text = { X = 215, Y = 20, Scale = 1.15 },
        },
        Subtitle = {
            Background = { Width = 431, Height = 37 },
            Text = { X = 8, Y = 3, Scale = 0.35 },
            PreText = { X = 425, Y = 3, Scale = 0.35 },
        },
        Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 0, Width = 431 },
        Navigation = {
            Rectangle = { Width = 431, Height = 18 },
            Offset = 5,
            Arrows = { Dictionary = "commonmenu", Texture = "shop_arrows_upanddown", X = 190, Y = -6, Width = 50, Height = 50 },
        },
        Description = {
            Bar = { Y = 4, Width = 431, Height = 4 },
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 30 },
            Text = { X = 8, Y = 10, Scale = 0.35 },
        },
    },
    Panels = {
        Grid = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 275 },
            Grid = { Dictionary = "pause_menu_pages_char_mom_dad", Texture = "nose_grid", X = 115.5, Y = 47.5, Width = 200, Height = 200 },
            Circle = { Dictionary = "mpinventory", Texture = "in_world_circle", X = 115.5, Y = 47.5, Width = 20, Height = 20 },
            Text = {
                Top = { X = 215.5, Y = 15, Scale = 0.35 },
                Bottom = { X = 215.5, Y = 250, Scale = 0.35 },
                Left = { X = 57.75, Y = 130, Scale = 0.35 },
                Right = { X = 373.25, Y = 130, Scale = 0.35 },
            },
        },
        Percentage = {
            Background = { Dictionary = "commonmenu", Texture = "gradient_bgd", Y = 4, Width = 431, Height = 76 },
            Bar = { X = 9, Y = 50, Width = 413, Height = 10 },
            Text = {
                Left = { X = 25, Y = 15, Scale = 0.35 },
                Middle = { X = 215.5, Y = 15, Scale = 0.35 },
                Right = { X = 398, Y = 15, Scale = 0.35 },
            },
        },
    },
}

function RageUIjh.SetScaleformParams(scaleform, data)
    data = data or {}
    for k, v in pairs(data) do
        PushScaleformMovieFunction(scaleform, v.name)
        if v.param then
            for _, par in pairs(v.param) do
                if math.type(par) == "integer" then
                    PushScaleformMovieFunctionParameterInt(par)
                elseif type(par) == "boolean" then
                    PushScaleformMovieFunctionParameterBool(par)
                elseif math.type(par) == "float" then
                    PushScaleformMovieFunctionParameterFloat(par)
                elseif type(par) == "string" then
                    PushScaleformMovieFunctionParameterString(par)
                end
            end
        end
        if v.func then
            v.func()
        end
        PopScaleformMovieFunctionVoid()
    end
end

---Visible
---@param Menu function
---@param Value boolean
---@return table
---@public
function RageUIjh.Visible(Menu, Value)
    if Menu ~= nil then
        if Menu() then
            if type(Value) == "boolean" then
                if Value then
                    if RageUIjh.CurrentMenu ~= nil then
			if RageUIjh.CurrentMenu.Closed ~= nil then
                            RageUIjh.CurrentMenu.Closed()
                        end
                        RageUIjh.CurrentMenu.Open = not Value
                    end
                    Menu:UpdateInstructionalButtons(Value);
                    Menu:UpdateCursorStyle();
                    RageUIjh.CurrentMenu = Menu
                    menuOpen = true
                else
                    menuOpen = false
                    RageUIjh.CurrentMenu = nil
                end
                Menu.Open = Value
                RageUIjh.Options = 0
                RageUIjh.ItemOffset = 0
                RageUIjh.LastControl = false
            else
                return Menu.Open
            end
        end
    end
end

function RageUIjh.CloseAll()
    menuOpen = false
    if RageUIjh.CurrentMenu ~= nil then
        local parent = RageUIjh.CurrentMenu.Parent
        while parent ~= nil do
            parent.Index = 1
            parent.Pagination.Minimum = 1
            parent.Pagination.Maximum = 10
            parent = parent.Parent
        end
        RageUIjh.CurrentMenu.Index = 1
        RageUIjh.CurrentMenu.Pagination.Minimum = 1
        RageUIjh.CurrentMenu.Pagination.Maximum = 10
        RageUIjh.CurrentMenu.Open = false
        RageUIjh.CurrentMenu = nil
    end
    RageUIjh.Options = 0
    RageUIjh.ItemOffset = 0
    ResetScriptGfxAlign()
end

---Banner
---@return nil
---@public
---@param Enabled boolean
function RageUIjh.Banner(Enabled, Glare)
    if type(Enabled) == "boolean" then
        if Enabled == true then


            if RageUIjh.CurrentMenu ~= nil then
                if RageUIjh.CurrentMenu() then


                    RageUIjh.ItemsSafeZone(RageUIjh.CurrentMenu)

                    if RageUIjh.CurrentMenu.Sprite then
                        RenderSprite(RageUIjh.CurrentMenu.Sprite.Dictionary, RageUIjh.CurrentMenu.Sprite.Texture, RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y, RageUIjh.Settings.Items.Title.Background.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.Settings.Items.Title.Background.Height, nil)
                    else
                        RenderRectangle(RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y, RageUIjh.Settings.Items.Title.Background.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.Settings.Items.Title.Background.Height, RageUIjh.CurrentMenu.Rectangle.R, RageUIjh.CurrentMenu.Rectangle.G, RageUIjh.CurrentMenu.Rectangle.B, RageUIjh.CurrentMenu.Rectangle.A)
                    end

                    RenderText(RageUIjh.CurrentMenu.Title, RageUIjh.CurrentMenu.X + RageUIjh.Settings.Items.Title.Text.X + (RageUIjh.CurrentMenu.WidthOffset / 2), RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Title.Text.Y, 1, RageUIjh.Settings.Items.Title.Text.Scale, 255, 255, 255, 255, 1)
                    RageUIjh.ItemOffset = RageUIjh.ItemOffset + RageUIjh.Settings.Items.Title.Background.Height
                end
            end
        end
    else
        error("Enabled is not boolean")
    end
end

---CloseAll -- TODO 
---@return nil
---@public
-- function RageUIjh:CloseAll()
--     RageUIjh.PlaySound(RageUIjh.Settings.Audio.Library, RageUIjh.Settings.Audio.Back)
--     RageUIjh.NextMenu = nil
--     RageUIjh.Visible(RageUIjh.CurrentMenu, false)
-- end

---Subtitle
---@return nil
---@public
function RageUIjh.Subtitle()
    if RageUIjh.CurrentMenu ~= nil then
        if RageUIjh.CurrentMenu() then
            RageUIjh.ItemsSafeZone(RageUIjh.CurrentMenu)
            if RageUIjh.CurrentMenu.Subtitle ~= "" then
                RenderRectangle(RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y + RageUIjh.ItemOffset, RageUIjh.Settings.Items.Subtitle.Background.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.Settings.Items.Subtitle.Background.Height + RageUIjh.CurrentMenu.SubtitleHeight, 0, 0, 0, 255)
                RenderText(RageUIjh.CurrentMenu.Subtitle, RageUIjh.CurrentMenu.X + RageUIjh.Settings.Items.Subtitle.Text.X, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Subtitle.Text.Y + RageUIjh.ItemOffset, 0, RageUIjh.Settings.Items.Subtitle.Text.Scale, 245, 245, 245, 255, nil, false, false, RageUIjh.Settings.Items.Subtitle.Background.Width + RageUIjh.CurrentMenu.WidthOffset)
                if RageUIjh.CurrentMenu.Index > RageUIjh.CurrentMenu.Options or RageUIjh.CurrentMenu.Index < 0 then
                    RageUIjh.CurrentMenu.Index = 1
                end
                RageUIjh.RefreshPagination()
                if RageUIjh.CurrentMenu.PageCounter == nil then
                    RenderText(RageUIjh.CurrentMenu.PageCounterColour .. RageUIjh.CurrentMenu.Index .. " / " .. RageUIjh.CurrentMenu.Options, RageUIjh.CurrentMenu.X + RageUIjh.Settings.Items.Subtitle.PreText.X + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Subtitle.PreText.Y + RageUIjh.ItemOffset, 0, RageUIjh.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                else
                    RenderText(RageUIjh.CurrentMenu.PageCounter, RageUIjh.CurrentMenu.X + RageUIjh.Settings.Items.Subtitle.PreText.X + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Subtitle.PreText.Y + RageUIjh.ItemOffset, 0, RageUIjh.Settings.Items.Subtitle.PreText.Scale, 245, 245, 245, 255, 2)
                end
                RageUIjh.ItemOffset = RageUIjh.ItemOffset + RageUIjh.Settings.Items.Subtitle.Background.Height
            end
        end
    end
end

---Background
---@return nil
---@public
function RageUIjh.Background()
    if RageUIjh.CurrentMenu ~= nil then
        if RageUIjh.CurrentMenu() then
            RageUIjh.ItemsSafeZone(RageUIjh.CurrentMenu)
            SetScriptGfxDrawOrder(0)
            RenderSprite(RageUIjh.Settings.Items.Background.Dictionary, RageUIjh.Settings.Items.Background.Texture, RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Background.Y + RageUIjh.CurrentMenu.SubtitleHeight, RageUIjh.Settings.Items.Background.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.ItemOffset, 0, 0, 0, 0, 255)
            SetScriptGfxDrawOrder(1)
        end
    end
end

---Description
---@return nil
---@public
function RageUIjh.Description()
    if RageUIjh.CurrentMenu ~= nil and RageUIjh.CurrentMenu.Description ~= nil then
        if RageUIjh.CurrentMenu() then
            RageUIjh.ItemsSafeZone(RageUIjh.CurrentMenu)
            RenderRectangle(RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Description.Bar.Y + RageUIjh.CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, RageUIjh.Settings.Items.Description.Bar.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.Settings.Items.Description.Bar.Height, 0, 0, 0, 255)
            RenderSprite(RageUIjh.Settings.Items.Description.Background.Dictionary, RageUIjh.Settings.Items.Description.Background.Texture, RageUIjh.CurrentMenu.X, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Description.Background.Y + RageUIjh.CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, RageUIjh.Settings.Items.Description.Background.Width + RageUIjh.CurrentMenu.WidthOffset, RageUIjh.CurrentMenu.DescriptionHeight, 0, 0, 0, 255)
            RenderText(RageUIjh.CurrentMenu.Description, RageUIjh.CurrentMenu.X + RageUIjh.Settings.Items.Description.Text.X, RageUIjh.CurrentMenu.Y + RageUIjh.Settings.Items.Description.Text.Y + RageUIjh.CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, 0, RageUIjh.Settings.Items.Description.Text.Scale, 255, 255, 255, 255, nil, false, false, RageUIjh.Settings.Items.Description.Background.Width + RageUIjh.CurrentMenu.WidthOffset - 8.0)
            RageUIjh.ItemOffset = RageUIjh.ItemOffset + RageUIjh.CurrentMenu.DescriptionHeight + RageUIjh.Settings.Items.Description.Bar.Y
        end
    end
end

---Render
---@param instructionalButton boolean
---@return nil
---@public
function RageUIjh.Render(instructionalButton)
    if RageUIjh.CurrentMenu ~= nil then
        if RageUIjh.CurrentMenu() then
            if RageUIjh.CurrentMenu.Safezone then
                ResetScriptGfxAlign()
            end
            if (instructionalButton) then
                DrawScaleformMovieFullscreen(RageUIjh.CurrentMenu.InstructionalScaleform, 255, 255, 255, 255, 0)
            end
            RageUIjh.CurrentMenu.Options = RageUIjh.Options
            RageUIjh.CurrentMenu.SafeZoneSize = nil
            RageUIjh.Controls()
            RageUIjh.Options = 0
            RageUIjh.StatisticPanelCount = 0
            RageUIjh.ItemOffset = 0
            if RageUIjh.CurrentMenu.Controls.Back.Enabled and RageUIjh.CurrentMenu.Closable then
                if RageUIjh.CurrentMenu.Controls.Back.Pressed then
                    RageUIjh.CurrentMenu.Controls.Back.Pressed = false
                    local Audio = RageUIjh.Settings.Audio
                    RageUIjh.PlaySound(Audio[Audio.Use].Back.audioName, Audio[Audio.Use].Back.audioRef)
                    collectgarbage()
                    if RageUIjh.CurrentMenu.Closed ~= nil then
                        RageUIjh.CurrentMenu.Closed()
                    end
                    if RageUIjh.CurrentMenu.Parent ~= nil then
                        if RageUIjh.CurrentMenu.Parent() then
                            RageUIjh.NextMenu = RageUIjh.CurrentMenu.Parent
                            RageUIjh.CurrentMenu:UpdateCursorStyle()
                        else
                            --print('xxx') Debug print
                            RageUIjh.NextMenu = nil
                            RageUIjh.Visible(RageUIjh.CurrentMenu, false)
                        end
                    else
                        --print('zz') Debug print
                        RageUIjh.NextMenu = nil
                        RageUIjh.Visible(RageUIjh.CurrentMenu, false)
                    end
                end
            end
            if RageUIjh.NextMenu ~= nil then
                if RageUIjh.NextMenu() then
                    RageUIjh.Visible(RageUIjh.CurrentMenu, false)
                    RageUIjh.Visible(RageUIjh.NextMenu, true)
                    RageUIjh.CurrentMenu.Controls.Select.Active = false
                    RageUIjh.NextMenu = nil
                    RageUIjh.LastControl = false
                end
            end
        end
    end
end

---ItemsDescription
---@param CurrentMenu table
---@param Description string
---@param Selected boolean
---@return nil
---@public
function RageUIjh.ItemsDescription(CurrentMenu, Description, Selected)
    ---@type table
    if Description ~= "" or Description ~= nil then
        local SettingsDescription = RageUIjh.Settings.Items.Description;
        if Selected and CurrentMenu.Description ~= Description then
            CurrentMenu.Description = Description or nil
            ---@type number
            local DescriptionLineCount = GetLineCount(CurrentMenu.Description, CurrentMenu.X + SettingsDescription.Text.X, CurrentMenu.Y + SettingsDescription.Text.Y + CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, 0, SettingsDescription.Text.Scale, 255, 255, 255, 255, nil, false, false, SettingsDescription.Background.Width + (CurrentMenu.WidthOffset - 5.0))
            if DescriptionLineCount > 1 then
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height * DescriptionLineCount
            else
                CurrentMenu.DescriptionHeight = SettingsDescription.Background.Height + 7
            end
        end
    end
end

---MouseBounds
---@param CurrentMenu table
---@param Selected boolean
---@param Option number
---@param SettingsButton table
---@return boolean
---@public
function RageUIjh.ItemsMouseBounds(CurrentMenu, Selected, Option, SettingsButton)
    ---@type boolean
    local Hovered = false
    Hovered = RageUIjh.IsMouseInBounds(CurrentMenu.X + CurrentMenu.SafeZoneSize.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SafeZoneSize.Y + CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height)
    if Hovered and not Selected then
        RenderRectangle(CurrentMenu.X, CurrentMenu.Y + SettingsButton.Rectangle.Y + CurrentMenu.SubtitleHeight + RageUIjh.ItemOffset, SettingsButton.Rectangle.Width + CurrentMenu.WidthOffset, SettingsButton.Rectangle.Height, 255, 255, 255, 20)
        if CurrentMenu.Controls.Click.Active then
            CurrentMenu.Index = Option
            local Audio = RageUIjh.Settings.Audio
            RageUIjh.PlaySound(Audio[Audio.Use].Error.audioName, Audio[Audio.Use].Error.audioRef)
        end
    end
    return Hovered;
end

---ItemsSafeZone
---@param CurrentMenu table
---@return nil
---@public
function RageUIjh.ItemsSafeZone(CurrentMenu)
    if not CurrentMenu.SafeZoneSize then
        CurrentMenu.SafeZoneSize = { X = 0, Y = 0 }
        if CurrentMenu.Safezone then
            CurrentMenu.SafeZoneSize = RageUIjh.GetSafeZoneBounds()
            SetScriptGfxAlign(76, 84)
            SetScriptGfxAlignParams(0, 0, 0, 0)
        end
    end
end

function RageUIjh.CurrentIsEqualTo(Current, To, Style, DefaultStyle)
    if (Current == To) then
        return Style;
    else
        return DefaultStyle or {};
    end
end

function RageUIjh.RefreshPagination()
    if (RageUIjh.CurrentMenu ~= nil) then
        if (RageUIjh.CurrentMenu.Index > 10) then
            local offset = RageUIjh.CurrentMenu.Index - 10
            RageUIjh.CurrentMenu.Pagination.Minimum = 1 + offset
            RageUIjh.CurrentMenu.Pagination.Maximum = 10 + offset
        else
            RageUIjh.CurrentMenu.Pagination.Minimum = 1
            RageUIjh.CurrentMenu.Pagination.Maximum = 10
        end
    end
end

function RageUIjh.IsVisible(menu, header, glare, instructional, items, panels)
    if (RageUIjh.Visible(menu)) then
        if (header == true) then
            RageUIjh.Banner(true, glare or false)
        end
        RageUIjh.Subtitle()
        if (items ~= nil) then
            items()
        end
        RageUIjh.Background();
        RageUIjh.Navigation();
        RageUIjh.Description();
        if (panels ~= nil) then
            panels()
        end
        RageUIjh.Render(instructional or false)
    end
end


---CreateWhile
---@param wait number
---@param menu table
---@param key number
---@param closure function
---@return void
---@public
function RageUIjh.CreateWhile(wait, menu, key, closure)
    Citizen.CreateThread(function()
        while (true) do
            Citizen.Wait(wait or 0.1)

            if (key ~= nil) then
                if IsControlJustPressed(1, key) then
                    RageUIjh.Visible(menu, not RageUIjh.Visible(menu))
                end
            end

            closure()
        end
    end)
end

---SetStyleAudio
---@param StyleAudio string
---@return void
---@public
function RageUIjh.SetStyleAudio(StyleAudio)
    RageUIjh.Settings.Audio.Use = StyleAudio or "RageUIjh"
end

function RageUIjh.GetStyleAudio()
    return RageUIjh.Settings.Audio.Use or "RageUIjh"
end

